import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../src/server/store';
import {Workspace,runSandbox} from '../src/server/workspace';
import {SwarmEngine,SWARM_TOOL_IDS,SPAWN_TOOL} from '../src/server/swarm';
import {Routines} from '../src/server/routines';
import {INITIAL_AGENTS} from '../src/data/initialData';
import {defaultSettings} from '../src/server/providers';
function setup(decide:(messages:any[])=>any=()=>({action:'final',reply:'Done'})){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vac-workspace-')),store=new Store(dir);let calls=0;
 const agent={...structuredClone(INITIAL_AGENTS[0]),id:'manager',workspaceId:'ws-default',displayName:'Coordinator',autonomyLevel:3,toolIds:[...SWARM_TOOL_IDS],llmConfig:{provider:'ollama',model:'fixture',temperature:0,maxTokens:1024}};
 store.put('agents','manager',agent);store.put('projects','project',{id:'project',workspaceId:'ws-default',name:'Project',description:'Test',members:[]});
 const engine=new SwarmEngine(store,()=>defaultSettings,(async(_p:any,m:any[])=>{calls++;return{decision:decide(m),receipt:{provider:'ollama',model:'fixture',inputTokens:10,outputTokens:10,cost:null}};})as any);
 const input={coordinatorId:'manager',projectId:'project',objective:'Complete test work',mode:'dynamic',allowedToolIds:[...SWARM_TOOL_IDS],browserPolicy:{allowedOrigins:['https://example.com']}};
 const create=(extra={})=>engine.create({...input,...extra},'test-'+crypto.randomUUID());
 const finish=async(id:string)=>{for(let i=0;i<60&&['queued','working','waiting_children'].includes(engine.get(id).status);i++)await engine.tick();return engine.get(id);};
 return{store,engine,input,create,finish,get calls(){return calls;},cleanup(){engine.stop();store.close();fs.rmSync(dir,{recursive:true,force:true});}};
}
test('full registry fits model context and completes a no-tool objective',async()=>{const f=setup();try{const r=await f.finish(f.create().id);assert.equal(r.status,'completed',r.result);assert.equal(f.calls,1);}finally{f.cleanup();}});
test('file versions isolate projects, reject traversal and stale overwrites; contracts require current run provenance',()=>{const f=setup();try{const w=f.engine.workspace;w.write('project','summary.json',Buffer.from('{"total":600}'),0,'owner');assert.throws(()=>w.write('project','summary.json',Buffer.from('x'),0,'owner'),/version changed/);assert.throws(()=>w.write('project','../escape',Buffer.from('x'),0,'owner'));assert.throws(()=>w.file('foreign','summary.json'));const job=f.create({contracts:[{name:'summary.json',kind:'json_equals',path:['total'],expected:600}]});assert.equal(w.contracts(job)[0].passed,false);w.write('project','summary.json',Buffer.from('{"total":600}'),1,'worker',job.id);assert.equal(w.contracts(job)[0].passed,true);assert.equal(w.file('project','summary.json',1).source,'owner');}finally{f.cleanup();}});
test('sandbox output writes versioned files atomically and reuses durable call receipts',async()=>{const f=setup();try{const w=new Workspace(f.store,async()=>({exitCode:0,stdout:'',stderr:'',files:[{name:'new.txt',base64:Buffer.from('new').toString('base64')},{name:'same.txt',base64:Buffer.from('changed').toString('base64')}]}));w.write('project','same.txt',Buffer.from('old'),0,'owner');const j=f.create();await w.execute(j,'node','tool-code',{code:'ignored',inputNames:[]},'code1',new AbortController().signal);assert.equal(w.file('project','same.txt').version,2);assert.equal(w.file('project','new.txt').version,1);assert.deepEqual(await w.execute(j,'node','tool-code',{code:'ignored'},'code1',new AbortController().signal),f.store.get('swarm-tool-results','code1'));}finally{f.cleanup();}});
test('memory proposals are excluded until approved and carry source provenance',async()=>{const f=setup();try{const w=f.engine.workspace,j=f.create();await w.execute(j,'node','tool-memory',{propose:'Use USD'},'memory1',new AbortController().signal);const read=await w.execute(j,'node','tool-memory',{},'memory2',new AbortController().signal);assert.deepEqual(read.output,[]);w.decideMemory(w.memories('project')[0].id,'approved');const accepted=await w.execute(j,'node','tool-memory',{},'memory3',new AbortController().signal);assert.equal(accepted.output[0].sourceRunId,j.id);}finally{f.cleanup();}});
const worker=(name:string,dependsOn:string[]=[])=>({name,role:'Analyst',objective:'Work '+name,instructions:'Report your dependency evidence',toolIds:[],acceptanceCriteria:['Report result'],dependsOn});
test('DAG dependencies wait for completed siblings, deliver evidence once, and reject cycles atomically',async()=>{for(const cycle of [false,true]){const seen:string[]=[];const f=setup(m=>{const root=m[0].content.includes('You are the coordinator.');if(root)return m.some(x=>x.content.startsWith('UNTRUSTED CHILD'))?{action:'final',reply:'Merged'}:{action:'tool',toolId:SPAWN_TOOL,parameters:{workers:[worker('A',cycle?['B']:[]),worker('B',['A'])]}};if(m[0].content.includes('You are B,')){assert.ok(seen.includes('A'));assert.ok(m.some(x=>x.content.startsWith('UNTRUSTED DEPENDENCY')));seen.push('B');}else seen.push('A');return{action:'final',reply:'Evidence'};});try{const r=await f.finish(f.create({allowedToolIds:[]}).id);if(cycle){assert.equal(r.status,'failed');assert.equal(r.nodes.length,1);}else{assert.equal(r.status,'completed');assert.deepEqual(seen,['A','B']);}}finally{f.cleanup();}}});
test('write connector pauses before any side effect and rejection never executes it',async()=>{const old=process.env.VAC_CONNECTOR_LOCAL_ENDPOINTS;process.env.VAC_CONNECTOR_LOCAL_ENDPOINTS='http://127.0.0.1:49999/tools';let connector:any;const f=setup(()=>({action:'tool',toolId:'tool-connector',parameters:{connectorId:connector.id,tool:'write',arguments:{value:600}}}));try{connector=f.engine.workspace.saveConnector({name:'Fixture',endpoint:process.env.VAC_CONNECTOR_LOCAL_ENDPOINTS,tools:[{name:'write',effect:'write'}]});const r=await f.finish(f.create({allowedToolIds:['tool-connector'],connectorIds:[connector.id]}).id);assert.equal(r.status,'waiting_approval');assert.equal(r.budget.toolCalls,0);const a=r.approvals![0];f.engine.decideApproval(a.id,'rejected');const done=await f.finish(r.id);assert.equal(done.status,'failed');assert.equal(done.budget.toolCalls,0);assert.throws(()=>f.engine.decideApproval(a.id,'approved'));}finally{if(old===undefined)delete process.env.VAC_CONNECTOR_LOCAL_ENDPOINTS;else process.env.VAC_CONNECTOR_LOCAL_ENDPOINTS=old;f.cleanup();}});
test('pinned skill routines survive scheduler recreation, prevent overlap, stop at cap and preserve versions',async()=>{const f=setup();try{let scheduler=new Routines(f.engine);const v1=scheduler.saveSkill({name:'Weekly',template:{...f.input,allowedToolIds:[]}}),v2=scheduler.saveSkill({name:'Weekly',template:{...f.input,objective:'New objective',allowedToolIds:[]}});assert.equal(v2.version,2);const routine=scheduler.create({skillId:v1.id,intervalMinutes:1,maxRuns:2,startsAt:new Date().toISOString()});scheduler.tick();let saved=f.store.get<any>('swarm-routines',routine.id);assert.equal(saved.runs,1);saved.nextAt=0;f.store.put('swarm-routines',saved.id,saved);scheduler=new Routines(f.engine);scheduler.tick();assert.equal(f.store.get<any>('swarm-routines',saved.id).runs,1);await f.finish(saved.lastRunId);scheduler.tick();saved=f.store.get<any>('swarm-routines',saved.id);assert.equal(saved.runs,2);assert.equal(saved.status,'completed');assert.equal(f.engine.get(saved.lastRunId).objective,f.input.objective);scheduler.tick();assert.equal(f.store.all('swarms').length,2);}finally{f.cleanup();}});
test('real sandbox generates documents and denies network, host filesystem and secrets',{skip:process.env.VAC_TEST_SANDBOX!=='1'},async()=>{
 const r=await runSandbox({language:'python',inputNames:[],files:[],code:`import os,json,socket\nfrom docx import Document\nfrom openpyxl import Workbook\nfrom pptx import Presentation\nfrom reportlab.pdfgen import canvas\nassert not os.path.exists('/Users/theo')\nassert 'VAC_ACCESS_TOKEN' not in os.environ\ntry:\n socket.create_connection(('1.1.1.1',443),timeout=1)\n raise AssertionError('network available')\nexcept OSError: pass\nd=Document();d.add_paragraph('Revenue 600');d.save('report.docx')\nw=Workbook();w.active.append(['Revenue',600]);w.save('report.xlsx')\np=Presentation();p.slides.add_slide(p.slide_layouts[0]).shapes.title.text='Revenue 600';p.save('report.pptx')\nc=canvas.Canvas('report.pdf');c.drawString(72,700,'Revenue 600');c.save()\nopen('summary.json','w').write(json.dumps({'total':600}))\nprint('isolation and documents passed')`},new AbortController().signal);assert.equal(r.exitCode,0,r.stderr);assert.equal(r.files.length,5);assert.match(r.stdout,/passed/);
});

test('concurrent sandbox output conflict rolls back all new artifacts',async()=>{const f=setup();try{const w=new Workspace(f.store,async()=>{f.engine.workspace.write('project','existing.txt',Buffer.from('concurrent'),1,'owner');return{exitCode:0,stdout:'',stderr:'',files:[{name:'new.txt',base64:Buffer.from('new').toString('base64')},{name:'existing.txt',base64:Buffer.from('changed').toString('base64')}]};});w.write('project','existing.txt',Buffer.from('old'),0,'owner');await assert.rejects(()=>w.execute(f.create(),'node','tool-code',{code:'ignored'},'conflict',new AbortController().signal),/version changed/);assert.throws(()=>w.file('project','new.txt'),/not found/);assert.equal(w.file('project','existing.txt').version,2);assert.equal(f.store.get('swarm-tool-results','conflict'),undefined);}finally{f.cleanup();}});

test('code-capable nodes receive real CSV headers, not guessed schemas',async()=>{let saw=false;const f=setup(m=>{const state=JSON.parse(m.find((x:any)=>x.content.startsWith('RUN STATE')).content.split('RUN STATE (server supplied): ')[1]);assert.equal(state.projectFiles[0].csvHeader,'product,revenue,cost');saw=true;return{action:'final',reply:'Inspected header'};});try{f.engine.workspace.write('project','sales.csv',Buffer.from('product,revenue,cost\nA,100,60\n'),0,'owner');const r=await f.finish(f.create({allowedToolIds:['tool-code']}).id);assert.equal(r.status,'completed');assert.equal(saw,true);}finally{f.cleanup();}});

test('deterministic report recipe validates CSV columns and produces inspectable document contents',{skip:process.env.VAC_TEST_SANDBOX!=='1'},async()=>{
 const f=setup();try{const w=f.engine.workspace;w.write('project','sales.csv',Buffer.from('product,revenue,cost\nA,100,60\nB,200,120\nC,300,180\n'),0,'owner');const j=f.create();await w.execute(j,'node','tool-code',{recipe:'tabular_report',inputName:'sales.csv',valueColumns:['revenue','cost'],outputPrefix:'report'},'recipe1',new AbortController().signal);assert.deepEqual(JSON.parse(Buffer.from(w.file('project','summary.json').base64,'base64').toString()),{revenue:600,cost:360,profit:240,rows:3});const files=w.files('project').filter(f=>f.runId===j.id).map(f=>w.file('project',f.name));const check=await runSandbox({language:'python',inputNames:[],files:files.map(({name,base64})=>({name,base64})),code:`from docx import Document\nfrom openpyxl import load_workbook\nfrom pptx import Presentation\nfrom pypdf import PdfReader\nassert '600' in '\\n'.join(p.text for p in Document('report.docx').paragraphs)\nassert load_workbook('report.xlsx').active.cell(2,1).value==600\nassert '600' in '\\n'.join(s.text for slide in Presentation('report.pptx').slides for s in slide.shapes if s.has_text_frame)\nassert '600' in PdfReader('report.pdf').pages[0].extract_text()\nprint('All four binary document formats inspected')`},new AbortController().signal);assert.equal(check.exitCode,0,check.stderr);await assert.rejects(()=>w.execute(j,'node','tool-code',{recipe:'tabular_report',inputName:'sales.csv',valueColumns:['missing'],outputPrefix:'bad'},'recipe2',new AbortController().signal),/column missing/);}finally{f.cleanup();}
});

test('interactive browser approvals bind the current target and are consumed exactly once',async()=>{
 const {SwarmBrowser}=await import('../src/server/browser');let calls=0;const requests:string[]=[];
 const f=setup(()=>{calls++;return calls===1?{action:'tool',toolId:'tool-browser',parameters:{action:'navigate',url:'https://example.com'}}:calls===2?{action:'tool',toolId:'tool-browser',parameters:{action:'fill',selector:'#name',value:'Synthetic'}}:calls===3?{action:'tool',toolId:'tool-browser',parameters:{action:'click',selector:'#submit'}}:{action:'final',reply:'Submitted test form'};});
 const browser=new SwarmBrowser(async r=>{requests.push(r.method);return{status:200,headers:{'content-type':'text/html'},body:Buffer.from(r.method==='POST'?'<h1>Saved</h1>':'<form method="POST" action="/save"><input id="name" name="name"><button id="submit">Save</button></form>')};});(f.engine as any).browsers=browser;
 try{let r=await f.finish(f.create({allowedToolIds:['tool-browser'],browserPolicy:{allowedOrigins:['https://example.com'],allowActions:true}}).id);assert.equal(r.status,'waiting_approval');assert.deepEqual(requests,['GET']);const first=r.approvals![0];assert.match(first.preview,/https:\/\/example.com/);f.engine.decideApproval(first.id,'approved');assert.throws(()=>f.engine.decideApproval(first.id,'approved'),/no longer/);r=await f.finish(r.id);assert.equal(r.status,'waiting_approval');assert.deepEqual(requests,['GET']);const next=r.approvals!.find(a=>a.status==='pending')!;f.engine.decideApproval(next.id,'approved');r=await f.finish(r.id);assert.equal(r.status,'completed',r.result);assert.deepEqual(requests,['GET','POST']);assert.ok(r.approvals!.every(a=>a.status==='consumed'));}finally{await browser.closeAll();f.cleanup();}
});

test('owner-defined workflow compiles hierarchy and dependencies atomically without planner calls',async()=>{
 const seen:string[]=[];const f=setup(m=>{seen.push(m[0].content.match(/^You are ([^,]+)/)?.[1]);return{action:'final',reply:'Verified subtask'};});
 try{const plan=[{...worker('Lead'),key:'lead'},{...worker('Leaf'),key:'leaf',parentKey:'lead'},{...worker('Review',['lead']),key:'review'}];const run=f.create({allowedToolIds:[],requiredDepth:2,plan});assert.equal(run.nodes.length,4);assert.equal(f.calls,0);assert.equal(run.nodes[1].status,'waiting_children');const done=await f.finish(run.id);assert.equal(done.status,'completed',done.result);assert.ok(seen.indexOf('Leaf')<seen.indexOf('Lead'));assert.ok(seen.indexOf('Lead')<seen.indexOf('Review'));const before=f.store.all('swarms').length;assert.throws(()=>f.create({plan:[{...worker('A'),key:'a',parentKey:'b'},{...worker('B'),key:'b',parentKey:'a'}]}),/cycle/);assert.equal(f.store.all('swarms').length,before);assert.throws(()=>f.create({plan:[{...worker('A',['b']),key:'a'},{...worker('B',['a']),key:'b'}]}),/cycle/);}finally{f.cleanup();}
});

test('ordered tool steps expose only the next authorized action and prevent repeated successful work',async()=>{
 const f=setup(m=>{const state=JSON.parse(m.find((x:any)=>x.content.startsWith('RUN STATE')).content.split('RUN STATE (server supplied): ')[1]);return state.nextRequiredTool?{action:'tool',toolId:state.nextRequiredTool,parameters:state.nextRequiredTool==='tool-calculator'?{operation:'add',a:2,b:3}:{}}:{action:'final',reply:'Sequence complete'};});try{const r=await f.finish(f.create({allowedToolIds:['tool-read-project','tool-calculator'],toolSequence:['tool-read-project','tool-calculator']}).id);assert.equal(r.status,'completed',r.result);assert.deepEqual(r.nodes[0].receipts.filter(r=>r.toolId).map(r=>r.toolId),['tool-read-project','tool-calculator']);assert.equal(r.budget.modelCalls,3);assert.throws(()=>f.create({allowedToolIds:['tool-calculator'],toolSequence:['tool-files']}),/grant/);}finally{f.cleanup();}
 const bad=setup(()=>({action:'tool',toolId:'tool-calculator',parameters:{operation:'add',a:1,b:2}}));try{const r=await bad.finish(bad.create({allowedToolIds:['tool-read-project','tool-calculator'],toolSequence:['tool-read-project','tool-calculator']}).id);assert.equal(r.status,'failed');assert.equal(r.budget.toolCalls,0);}finally{bad.cleanup();}
});

test('connector argument schemas reach the model and reject malformed values before approval or dispatch',()=>{const f=setup();try{const c=f.engine.workspace.saveConnector({name:'Typed gateway',endpoint:'https://gateway.example/tools',tools:[{name:'save',effect:'write',inputSchema:{type:'object',properties:{revenue:{type:'number'},profit:{type:'number'}},required:['revenue','profit'],additionalProperties:false}}]});const j=f.create({connectorIds:[c.id]});const def:any=f.engine.workspace.connectorDefinition(j);assert.equal(def.schema.properties.arguments.properties.revenue.type,'number');assert.throws(()=>f.engine.workspace.connector(j,{connectorId:c.id,tool:'save',arguments:{revenue:{value:600},profit:240}}));assert.equal(f.engine.workspace.connector(j,{connectorId:c.id,tool:'save',arguments:{revenue:600,profit:240}}).write,true);assert.throws(()=>f.engine.workspace.connector(j,{connectorId:c.id,tool:'save',arguments:{revenue:600,profit:240,extra:'no'}}));}finally{f.cleanup();}});

test('planned depth confusion receives one factual correction without bypassing tool evidence',async()=>{for(const persistent of [false,true]){let rootCalls=0;const f=setup(m=>{if(!m[0].content.includes('You are the coordinator.'))return{action:'final',reply:'Child finished'};rootCalls++;return rootCalls===1||persistent?{action:'blocked',reason:'Depth cap prevents further tool execution'}:rootCalls===2?{action:'tool',toolId:'tool-calculator',parameters:{operation:'add',a:2,b:3}}:{action:'final',reply:'5'};});try{const r=await f.finish(f.create({allowedToolIds:['tool-calculator'],toolSequence:['tool-calculator'],plan:[{...worker('Child'),key:'child'}]}).id);assert.equal(r.status,persistent?'blocked':'completed',r.result);assert.equal(r.events.filter(e=>e.type==='BLOCK_REVIEW').length,1);assert.equal(r.budget.toolCalls,persistent?0:1);}finally{f.cleanup();}}});

test('rich dynamic context retains room for child evidence and typed connectors without raising the envelope',async()=>{
 let rootCalls=0;const f=setup(m=>{if(!m[0].content.includes('You are the coordinator.'))return{action:'final',reply:'Evidence '.repeat(120)};rootCalls++;return rootCalls===1?{action:'tool',toolId:SPAWN_TOOL,parameters:{workers:[worker('A'),worker('B'),worker('C')]}}:rootCalls===2?{action:'tool',toolId:'tool-select-tools',parameters:{toolIds:['tool-read-project','tool-calculator','tool-memory']}}:rootCalls===3?{action:'tool',toolId:'tool-read-project',parameters:{}}:rootCalls===4?{action:'tool',toolId:'tool-calculator',parameters:{operation:'subtract',a:600,b:360}}:rootCalls===5?{action:'tool',toolId:'tool-memory',parameters:{propose:'Retain verified totals.'}}:{action:'final',reply:'Verified 240'};});
 try{const c=f.engine.workspace.saveConnector({name:'Typed connector',endpoint:'https://gateway.example/tools',tools:[{name:'save',effect:'write',inputSchema:{type:'object',properties:{revenue:{type:'number'},profit:{type:'number'}},required:['revenue','profit'],additionalProperties:false}}]});const contracts=Array.from({length:6},(_,i)=>({name:`file${i}.json`,kind:'json_equals',path:['total'],expected:600}));const r=f.create({objective:'Prepare a source-backed sales report with verified current-run artifacts and bounded collaboration. '.repeat(16),connectorIds:[c.id],contracts,requiredToolIds:['tool-read-project','tool-calculator','tool-memory']});for(let i=0;i<20;i++)f.engine.workspace.write('project',`file${i}.json`,Buffer.from('{"total":600}'),0,'fixture',r.id);const done=await f.finish(r.id);assert.equal(done.status,'completed',done.result);assert.equal(rootCalls,6);assert.ok(done.verification?.every(v=>v.passed));}finally{f.cleanup();}
});

test('Deep Agents generates and atomically compiles a workflow using the shared budget',async()=>{
 const f=setup(m=>m[0].content.includes('VAC workflow planner')?{action:'tool',toolId:'submit_workflow',parameters:{plan:[{...worker('Leaf'),key:'leaf',parentKey:'',agentId:''}],toolSequence:[]}}:{action:'final',reply:'Done'});
 try{const r=await f.finish(f.create({harness:'deepagents',allowedToolIds:[]}).id);assert.equal(r.status,'completed',r.result);assert.equal(r.nodes.length,2);assert.equal(r.budget.modelCalls,3);assert.equal(r.budget.toolCalls,1);assert.equal(r.budget.spawned,1);assert.equal(r.harnessResult?.harness,'deepagents@1.14.0');assert.equal(r.nodes[0].receipts.filter(x=>x.phase==='harness-planning').length,1);assert.throws(()=>f.create({harness:'deepagents',plan:[{...worker('Leaf'),key:'leaf'}]}),/generates its own/);}finally{f.cleanup();}
});

test('invalid harness plans never create nodes and repeated attempts stop at the planning cap',async()=>{
 const f=setup(()=>({action:'tool',toolId:'submit_workflow',parameters:{plan:[{...worker('Bad'),key:'bad',parentKey:'',agentId:'',toolIds:['tool-code']}],toolSequence:[]}}));
 try{const r=await f.finish(f.create({harness:'deepagents',allowedToolIds:[]}).id);assert.notEqual(r.status,'completed');assert.equal(r.nodes.length,1);assert.equal(r.budget.spawned,0);assert.equal(r.budget.modelCalls,4);assert.equal(f.store.all('swarm-nodes').length,1);assert.match(r.nodes[0].result!,/planning limit/);}finally{f.cleanup();}
});

test('harness cannot bypass root context budgets or call filesystem and task tools',async()=>{
 for(const toolId of ['execute','task','write_file']){const f=setup(()=>({action:'tool',toolId,parameters:{}}));try{const r=await f.finish(f.create({harness:'deepagents'}).id);assert.equal(r.status,'failed');assert.equal(r.nodes.length,1);assert.equal(r.budget.toolCalls,0);assert.match(r.nodes[0].result!,/unavailable tool|planning authority/);}finally{f.cleanup();}}
 const f=setup();try{const r=await f.finish(f.create({harness:'deepagents',limits:{maxInputTokens:4096}}).id);assert.equal(r.status,'budget_exhausted');assert.equal(f.calls,0);}finally{f.cleanup();}
});

test('cancellation during harness inference cannot compile or resurrect a plan',async()=>{
 const f=setup();let release:any,started:any;const entered=new Promise<void>(r=>started=r);
 (f.engine as any).inference=async()=>{started();await new Promise<void>(r=>release=r);return{decision:{action:'tool',toolId:'submit_workflow',parameters:{plan:[{...worker('Leaf'),key:'leaf',parentKey:'',agentId:''}],toolSequence:[]}},receipt:{inputTokens:12,outputTokens:10}};};
 try{const r=f.create({harness:'deepagents',allowedToolIds:[]});const ticking=f.engine.tick();await entered;f.engine.cancel(r.id);release();await ticking;const done=f.engine.get(r.id);assert.equal(done.status,'cancelled');assert.equal(done.nodes.length,1);assert.equal(done.budget.spawned,0);assert.equal(done.budget.modelCalls,1);}finally{f.cleanup();}
});

test('harness corrects aggregate topology feedback without persisting rejected workers',async()=>{
 let planning=0;const f=setup(m=>{
  if(!m[0].content.includes('VAC workflow planner'))return{action:'final',reply:'Done'};
  planning++;if(planning===1)return{action:'tool',toolId:'write_todos',parameters:{todos:[{content:'Create nested workflow',status:'in_progress'}]}};
  return{action:'tool',toolId:'submit_workflow',parameters:{plan:[{...worker('Lead'),key:'lead',parentKey:'',agentId:'',dependsOn:planning===2?['leaf']:[]},{...worker('Leaf'),key:'leaf',parentKey:'lead',agentId:'',dependsOn:planning===2?['lead']:[]}],toolSequence:[]}};
 });try{const r=await f.finish(f.create({harness:'deepagents',allowedToolIds:[],requiredDepth:2}).id);assert.equal(r.status,'completed',r.result);assert.equal(r.nodes.length,3);assert.equal(r.budget.spawned,2);assert.equal(r.budget.toolCalls,3);assert.equal(r.events.filter(e=>e.type==='HARNESS_REJECTED').length,1);assert.match(r.events.find(e=>e.type==='HARNESS_REJECTED')!.detail,/supervisor.*sibling/);assert.equal(f.store.all('swarm-nodes').length,3);}finally{f.cleanup();}
});

test('generated root sequences are revalidated before workflow compilation',async()=>{
 const f=setup(()=>({action:'tool',toolId:'submit_workflow',parameters:{plan:[{...worker('Leaf'),key:'leaf',parentKey:'',agentId:''}],toolSequence:['tool-calculator','tool-calculator']}}));try{const r=await f.finish(f.create({harness:'deepagents',allowedToolIds:['tool-calculator']}).id);assert.equal(r.status,'failed');assert.equal(r.nodes.length,1);assert.equal(r.budget.spawned,0);assert.ok(r.events.some(e=>e.type==='HARNESS_REJECTED'&&e.detail.includes('unique')));}finally{f.cleanup();}
});
