import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {SwarmView} from '../swarmTypes';

export function SwarmWorkspace({projectId,current,onError}:{projectId:string;current?:SwarmView;onError:(s:string)=>void}){
 const [files,F]=useState<any[]>([]),[memories,M]=useState<any[]>([]),[skills,S]=useState<any[]>([]),[routines,R]=useState<any[]>([]),[profiles,P]=useState<any[]>([]),[connectors,C]=useState<any[]>([]);
 const [discovered,D]=useState('');
 const [skillName,N]=useState(''),[skillId,I]=useState(''),[minutes,T]=useState(60),[maxRuns,X]=useState(1),[config,G]=useState('');
 const refresh=async()=>{if(!projectId)return;const [f,m,s,r,p,c]=await Promise.all([api(`/api/projects/${projectId}/files`),api(`/api/projects/${projectId}/swarm-memory`),api(`/api/projects/${projectId}/skills`),api(`/api/projects/${projectId}/routines`),api(`/api/projects/${projectId}/browser-profiles`),api('/api/swarm-connectors')]);F(f);M(m);S(s);R(r);P(p);C(c);};
 const act=async(fn:()=>Promise<unknown>)=>{try{await fn();await refresh();}catch(e){onError(String(e));}};
 useEffect(()=>{void act(refresh);const t=setInterval(()=>void act(refresh),5000);return()=>clearInterval(t);},[projectId]);
 const upload=async(file:File)=>{if(file.size>6*1024*1024)throw new Error('Maximum upload is 6 MiB');const data=await file.arrayBuffer();let binary='';for(const b of new Uint8Array(data))binary+=String.fromCharCode(b);await api(`/api/projects/${projectId}/files`,'POST',{name:file.name,base64:btoa(binary),expectedVersion:files.find(f=>f.name===file.name)?.version||0});};
 const saveSkill=async()=>{if(!current)throw new Error('Select a run first');const {coordinatorId,projectId,objective,mode,allowedToolIds,requiredToolIds,requiredDepth,browserPolicy,limits,contracts,connectorIds,plan,toolSequence,semanticReview,harness}=current;await api('/api/swarm-skills','POST',{name:skillName,template:{coordinatorId,projectId,objective,mode,allowedToolIds,requiredToolIds,requiredDepth,browserPolicy,limits,contracts,connectorIds,plan,toolSequence,semanticReview,harness}});N('');};
 return <section aria-label="Persistent project workspace" className="bg-white rounded-2xl border p-5 space-y-5">
 <h2 className="font-semibold">Project workspace</h2>
 <div><h3 className="text-sm font-medium">Files and deliverables</h3><label className="block text-xs my-2">Upload file (up to 6 MiB)<input aria-label="Upload project file" type="file" className="block mt-2" onChange={e=>{const f=e.target.files?.[0];if(f)void act(()=>upload(f));e.target.value='';}}/></label>{files.map(f=><div key={f.id} className="text-xs py-2 flex justify-between gap-2"><a className="underline break-all" href={`/api/projects/${projectId}/files/download?name=${encodeURIComponent(f.name)}&version=${f.version}`}>{f.name}</a><span>v{f.version} · {f.bytes} bytes</span></div>)}</div>
 <details><summary className="text-sm cursor-pointer">Memory proposals ({memories.filter(m=>m.status==='proposed').length})</summary>{memories.map(m=><article key={m.id} className="text-xs border rounded p-3 mt-2"><p>{m.content}</p><p className="text-slate-500 mt-1">{m.status} · source run {m.sourceRunId}</p>{m.status==='proposed'&&<div className="flex gap-3 mt-2">{['approved','rejected'].map(decision=><button className="underline" key={decision} onClick={()=>void act(()=>api(`/api/swarm-memory/${m.id}/decision`,'POST',{decision}))}>{decision==='approved'?'Approve memory':'Reject'}</button>)}</div>}</article>)}</details>
 <details><summary className="text-sm cursor-pointer">Reusable skills and scheduled routines</summary><p className="text-xs text-slate-500 my-2">Save the selected run configuration as an immutable skill version. Schedules run only while this app is running; missed intervals do not accumulate. Each run retains the same tool grants and limits. External writes still require approval.</p><div className="flex gap-2"><input aria-label="Skill name" className="border rounded p-2 min-w-0 text-xs" value={skillName} onChange={e=>N(e.target.value)} placeholder="Skill name"/><button disabled={!current||!skillName.trim()} className="text-xs underline disabled:opacity-40" onClick={()=>void act(saveSkill)}>Save selected run as skill</button></div>
 <select aria-label="Routine skill" className="border rounded p-2 text-xs w-full my-2" value={skillId} onChange={e=>I(e.target.value)}><option value="">Choose pinned skill version</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name} v{s.version}</option>)}</select><div className="flex gap-2 text-xs"><label>Interval (minutes)<input type="number" min={1} className="border rounded p-2 w-full" value={minutes} onChange={e=>T(+e.target.value)}/></label><label>Maximum runs<input type="number" min={1} max={100} className="border rounded p-2 w-full" value={maxRuns} onChange={e=>X(+e.target.value)}/></label></div><button disabled={!skillId} className="text-xs underline my-2" onClick={()=>void act(()=>api('/api/swarm-routines','POST',{skillId,intervalMinutes:minutes,maxRuns,startsAt:new Date().toISOString()}))}>Authorize routine, starting now</button>{routines.map(r=><div key={r.id} className="text-xs border rounded p-2 mt-1">{skills.find(s=>s.id===r.skillId)?.name} · {r.status} · {r.runs}/{r.maxRuns} runs {r.status==='active'&&<button className="underline ml-2" onClick={()=>void act(()=>api(`/api/swarm-routines/${r.id}/pause`,'POST',{}))}>Pause</button>}{r.error&&<p>{r.error}</p>}</div>)}</details>
 <details><summary className="text-sm cursor-pointer">Saved browser sessions</summary><p className="text-xs my-2">Sessions are private to this project, expire after seven idle days and allow one active user at a time.</p>{profiles.map(p=><div className="text-xs flex justify-between py-2" key={p.profileId}>{p.profileId}<button className="underline" onClick={()=>void act(()=>api(`/api/projects/${projectId}/browser-profiles/${p.profileId}`,'DELETE'))}>Delete saved session</button></div>)}</details>
 <details><summary className="text-sm cursor-pointer">Approved connector gateway</summary><p className="text-xs my-2">Configure an MCP Streamable HTTP connector with protocol: "mcp", or a legacy JSON-RPC gateway. Credentials are server environment variables; never put secrets in this form. Discovery lists tools; it never grants access automatically. MCP currently supports bounded HTTP tool sessions; OAuth and local stdio servers are not enabled.</p>{connectors.map(c=><div className="text-xs border rounded p-2 my-2" key={c.id}><p>{c.name} · {c.enabled?'enabled':'disabled'}</p><p className="break-all">ID: {c.id}</p>{c.enabled&&c.protocol==='mcp'&&<button className="underline mr-3" onClick={()=>void act(async()=>{const d=await api(`/api/swarm-connectors/${c.id}/discover`,'POST',{});D(JSON.stringify(d,null,2));})}>Discover tools</button>}{c.enabled&&<button className="underline" onClick={()=>void act(()=>api(`/api/swarm-connectors/${c.id}/disable`,'POST',{}))}>Disable</button>}</div>)}{discovered&&<pre aria-label="Discovered MCP tools" className="text-xs max-h-64 overflow-auto whitespace-pre-wrap break-all">{discovered}</pre>}<textarea aria-label="Connector configuration" className="border rounded p-2 w-full text-xs" rows={5} value={config} onChange={e=>G(e.target.value)} placeholder={'{"name":"My gateway","endpoint":"https://gateway.example/tools","tools":[{"name":"lookup","effect":"read"}]}'} /><button disabled={!config} className="text-xs underline" onClick={()=>void act(()=>api('/api/swarm-connectors','POST',JSON.parse(config)))}>Approve connector configuration</button></details>
 </section>;
}
