import { SwarmWorkspace } from './SwarmWorkspace';
import React, { useEffect, useState } from 'react';
import { Network, Play, Square, ChevronRight, Bot, CheckCircle2 } from 'lucide-react';
import type { Agent, Project } from '../types';
import type { SwarmView as Run, SwarmLimits } from '../swarmTypes';
import { api } from '../lib/api';

const live = (r: Run) => ['queued', 'working', 'waiting_children','waiting_approval'].includes(r.status);
const label = (s: string) => s.replaceAll('_', ' ');
const toolNames: Record<string,string> = { 'tool-read-project':'Read project', 'tool-calculator':'Calculator', 'tool-web-search':'Web search', 'tool-browser':'Browser automation','tool-files':'Read project files','tool-write-file':'Write draft files','tool-code':'Sandboxed Python / shell','tool-memory':'Project memory','tool-connector':'Approved connectors','tool-peer':'Message teammates','tool-evidence':'Read teammate evidence' };
export function SwarmView({ agents, projects }: { agents: Agent[]; projects: Project[] }) {
  const [runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState('');
  const [coordinator,setCoordinator]=useState(''),[project,setProject]=useState(()=>localStorage.getItem('vac-swarm-project')||''),[objective,setObjective]=useState('');
  const [mode,setMode]=useState<'manual'|'dynamic'|'hybrid'>('hybrid');
  const [limits,setLimits]=useState<SwarmLimits>(),[tools,setTools]=useState(['tool-read-project','tool-calculator']);
  const [error,setError]=useState(''),[submitting,setSubmitting]=useState(false),[advanced,setAdvanced]=useState(false);
  const [harness,setHarness]=useState('native');
  const [plan,setPlan]=useState('[]'),[sequence,setSequence]=useState('');
  const [contracts,setContracts]=useState('[]'),[connectorIds,setConnectorIds]=useState(''),[profileId,setProfileId]=useState('');
  const [requiredDepth,setRequiredDepth]=useState(0);
  const [browserOrigins,setBrowserOrigins]=useState(''),[browserActions,setBrowserActions]=useState(false);
  const [requireVerification,setRequireVerification]=useState(false);
  const [modelConcurrency,setModelConcurrency]=useState(2);
  const [expanded,setExpanded]=useState<string>();
  useEffect(()=>{let disposed=false;
    const poll=async()=>{try{const value=await api<Run[]>('/api/swarms');if(!disposed)setRuns(value);}catch(e){if(!disposed)setError(String(e));}};
    void api<{defaults:SwarmLimits;localInferenceConcurrency:number}>('/api/swarms/config').then(c=>{if(!disposed){setLimits(c.defaults);setModelConcurrency(c.localInferenceConcurrency);}}).catch(e=>setError(String(e)));
    void poll();const timer=setInterval(()=>void poll(),1500);return()=>{disposed=true;clearInterval(timer);};
  },[]);
  useEffect(()=>{setCoordinator(old=>agents.some(a=>a.id===old)?old:agents.find(a=>a.llmConfig.provider==='ollama' || a.llmConfig.localSource==='ollama')?.id||agents[0]?.id||'');setProject(old=>projects.some(p=>p.id===old)?old:projects[0]?.id||'');},[agents,projects]);
  useEffect(()=>{if(project)localStorage.setItem('vac-swarm-project',project);},[project]);
  const current=runs.find(r=>r.id===selected&&r.projectId===project)||runs.find(r=>r.projectId===project);
  const treeNodes:Run['nodes']=[];const visited=new Set<string>();
  const visit=(parentId?:string)=>{for(const n of current?.nodes||[]){if(n.parentId===parentId&&!visited.has(n.id)){visited.add(n.id);treeNodes.push(n);visit(n.id);}}};visit();
  const selectedAgent=agents.find(a=>a.id===coordinator);
  const ollama=selectedAgent?.llmConfig.provider==='ollama'||selectedAgent?.llmConfig.localSource==='ollama'||selectedAgent?.llmConfig.model.startsWith('ollama:');
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!limits)return;setSubmitting(true);setError('');try{const r=await api<Run>('/api/swarms','POST',{harness,coordinatorId:coordinator,projectId:project,objective,mode,allowedToolIds:tools,requiredToolIds:requireVerification?tools:[],requiredDepth,toolSequence:sequence.split(/[\s,]+/).filter(Boolean),plan:JSON.parse(plan),contracts:JSON.parse(contracts),connectorIds:connectorIds.split(/[\s,]+/).filter(Boolean),browserPolicy:{allowedOrigins:browserOrigins.split(/[\s,]+/).filter(Boolean),allowActions:browserActions,...(profileId?{profileId}:{})},limits});setRuns(old=>[r,...old.filter(o=>o.id!==r.id)]);setSelected(r.id);setObjective('');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSubmitting(false);}};
  const action=async(kind:string)=>{if(!current)return;try{const r=await api<Run>(`/api/swarms/${current.id}/${kind}`,'POST',{});setRuns(old=>old.map(o=>o.id===r.id?r:o));}catch(e){setError(String(e));}};
  return <main className="flex-1 min-w-0 overflow-auto p-5 md:p-8" aria-label="AI Swarm workspace">
    <header className="flex items-center gap-3 mb-7"><div className="p-3 bg-amber-100 rounded-2xl"><Network className="text-amber-800"/></div><div><h1 className="text-2xl font-semibold">AI Swarm</h1><p className="text-sm text-slate-500">Coordinate your team and create specialists for the work at hand.</p></div></header>
    {error&&<p role="alert" className="p-3 mb-4 rounded-xl bg-red-50 text-red-800">{error}</p>}
    <div className="grid xl:grid-cols-[360px_1fr] gap-6 items-start">
      <section className="space-y-5">
        <form onSubmit={submit} className="bg-white rounded-2xl border border-slate-200 p-5 space-y-4">
          <h2 className="font-semibold">Start a swarm</h2>
          <label className="block text-sm">Project<select aria-label="Swarm project" value={project} onChange={e=>setProject(e.target.value)} className="mt-1 border rounded-lg p-2 w-full">{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
          <label className="block text-sm">Coordinator<select aria-label="Swarm coordinator" value={coordinator} onChange={e=>setCoordinator(e.target.value)} className="mt-1 border rounded-lg p-2 w-full">{agents.map(a=><option key={a.id} value={a.id}>{a.displayName}</option>)}</select></label>
          {!ollama&&<p className="text-xs text-amber-800 bg-amber-50 rounded-lg p-3">Choose an Ollama model for this agent in Team before starting a swarm.</p>}
          <label className="block text-sm">Team composition<select aria-label="Team composition" value={mode} onChange={e=>setMode(e.target.value as typeof mode)} className="mt-1 border rounded-lg p-2 w-full"><option value="hybrid">Existing agents + temporary specialists</option><option value="dynamic">Temporary specialists</option><option value="manual">Existing agents only</option></select></label>
          <label className="block text-sm">Objective<textarea aria-label="Swarm objective" required maxLength={12000} value={objective} onChange={e=>setObjective(e.target.value)} rows={5} placeholder="Describe the deliverable, constraints and what a good result must include…" className="mt-1 border rounded-lg p-3 w-full text-sm"/></label>
          <fieldset><legend className="text-sm mb-2">Tools this swarm may use</legend>{Object.entries(toolNames).map(([id,name])=><label className="flex gap-2 items-center text-sm py-1" key={id}><input type="checkbox" checked={tools.includes(id)} onChange={e=>setTools(old=>e.target.checked?[...old,id]:old.filter(t=>t!==id))}/>{name}</label>)}<p className="text-xs text-slate-500 mt-2">Search may use paid provider credits. Your configured provider and daily allowance still apply.</p></fieldset>
          {tools.includes('tool-browser')&&<fieldset className="border rounded-lg p-3 space-y-3"><legend className="text-sm">Browser permissions</legend><label className="block text-xs">Approved site origins (one per line)<textarea aria-label="Browser origins" value={browserOrigins} onChange={e=>setBrowserOrigins(e.target.value)} placeholder="https://example.com" className="border rounded p-2 w-full mt-1" required/></label><label className="block text-xs">Saved session name (optional)<input aria-label="Browser profile" className="border rounded p-2 w-full" value={profileId} onChange={e=>setProfileId(e.target.value)}/></label><label className="flex gap-2 text-xs"><input type="checkbox" checked={browserActions} onChange={e=>setBrowserActions(e.target.checked)}/>Allow interactive actions and form submissions on these sites</label><p className="text-xs text-slate-500">Each agent gets an isolated session. Without actions, only reading and link navigation are available. Each interactive action pauses for approval before execution. Use exact origins without trailing slashes; private networks are blocked.</p></fieldset>}
          {tools.includes('tool-connector')&&<label className="block text-xs">Approved connector IDs<textarea className="border rounded p-2 w-full" value={connectorIds} onChange={e=>setConnectorIds(e.target.value)}/></label>}
          <label className="block text-xs">Planning engine<select aria-label="Planning engine" value={harness} onChange={e=>setHarness(e.target.value)} className="border rounded p-2 w-full"><option value="native">Native step-by-step decisions</option><option value="deepagents">Deep Agents — bounded workflow planner (experimental)</option></select></label><details><summary className="text-xs cursor-pointer">Repeatable workflow plan (optional)</summary><p className="text-xs my-2">Leave [] for autonomous planning. A supplied plan fixes workers, parent keys, dependencies and evidence requirements; each worker still uses its model to execute its task.</p><textarea aria-label="Workflow plan" rows={5} value={plan} onChange={e=>setPlan(e.target.value)} className="border rounded p-2 w-full text-xs"/><label className="block text-xs mt-2">Coordinator tool sequence (optional IDs, in order)<input aria-label="Coordinator tool sequence" value={sequence} onChange={e=>setSequence(e.target.value)} className="border rounded p-2 w-full"/></label></details>
          <details><summary className="text-xs cursor-pointer">Deliverable contracts</summary><p className="text-xs my-2">Completion requires these files to be produced by this run and pass the checks.</p><textarea aria-label="Deliverable contracts" className="border rounded p-2 w-full text-xs" rows={5} value={contracts} onChange={e=>setContracts(e.target.value)} placeholder={'[{"name":"summary.json","kind":"json_equals","path":["total"],"expected":600}]'}/></details>
          <label className="flex items-start gap-2 text-xs text-slate-600"><input type="checkbox" checked={requireVerification} onChange={e=>setRequireVerification(e.target.checked)}/>Require the coordinator to also verify using every selected tool</label>
          {limits&&<><div className="grid grid-cols-2 gap-3">{(['maxAgents','concurrency','maxModelCalls','maxMinutes'] as const).map(k=><label key={k} className="text-xs text-slate-600">{{maxAgents:'Total agents',concurrency:'Concurrent workers',maxModelCalls:'Model calls',maxMinutes:'Time limit (min)'}[k]}<input aria-label={k} type="number" min={1} max={{maxAgents:17,concurrency:4,maxModelCalls:128,maxMinutes:120}[k]} value={limits[k]} onChange={e=>setLimits({...limits,[k]:Number(e.target.value)})} className="border rounded-lg p-2 w-full mt-1"/></label>)}</div>
          <label className="block text-xs text-slate-600">Minimum verified delegation depth (0 = no requirement)<input aria-label="Required delegation depth" type="number" min={0} max={limits.maxDepth} value={requiredDepth} onChange={e=>setRequiredDepth(Number(e.target.value))} className="border rounded-lg p-2 w-full mt-1"/></label>
          <button type="button" onClick={()=>setAdvanced(!advanced)} className="text-xs underline">{advanced?'Hide':'Show'} resource limits</button>
          {advanced&&<div className="grid grid-cols-2 gap-3">{(['maxSandboxRuns','maxDepth','maxBrowserSteps','maxBrowserRequests','maxCallsPerAgent','maxInputTokens','maxOutputTokens','maxTokensPerCall','maxToolCalls','maxSearchAttempts'] as const).map(k=><label key={k} className="text-xs text-slate-600">{{maxSandboxRuns:'Sandbox executions',maxDepth:'Delegation depth (1–4)',maxBrowserSteps:'Browser steps',maxBrowserRequests:'Browser network requests',maxCallsPerAgent:'Calls per agent',maxInputTokens:'Input reservation',maxOutputTokens:'Output reservation',maxTokensPerCall:'Output per call',maxToolCalls:'Tool calls',maxSearchAttempts:'Search attempts'}[k]}<input aria-label={k} type="number" min={0} value={limits[k]} onChange={e=>setLimits({...limits,[k]:Number(e.target.value)})} className="border rounded-lg p-2 w-full mt-1"/></label>)}</div>}</>}
          <p className="text-xs text-slate-500">Ollama execution is shared across the workspace, with at most {modelConcurrency} simultaneous model requests. Specialists may delegate up to the configured depth. All descendants share the same resource limits.</p>
          <button disabled={!objective.trim()||!project||!coordinator||!ollama||submitting||!limits} className="flex items-center justify-center gap-2 w-full bg-slate-900 text-white rounded-xl p-3 disabled:opacity-40"><Play size={15}/>{submitting?'Starting…':'Start swarm'}</button>
        </form>
        <SwarmWorkspace projectId={project} current={current} onError={setError}/>
        <div className="bg-white rounded-2xl border border-slate-200 p-4"><h2 className="font-semibold mb-3">Recent swarms</h2>{runs.length===0&&<p className="text-sm text-slate-500">Your first swarm will appear here.</p>}{runs.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`text-left w-full rounded-lg p-3 mb-1 ${current?.id===r.id?'bg-amber-50':'hover:bg-slate-50'}`}><span className="block text-sm truncate">{r.objective}</span><span className="text-xs text-slate-500">{label(r.status)} · {r.nodes.length} agents</span></button>)}</div>
      </section>
      <section className="min-w-0 space-y-5">
        {!current?<div className="bg-white border border-slate-200 rounded-2xl p-12 text-center"><Network size={38} className="mx-auto text-slate-300 mb-4"/><h2 className="font-semibold">One objective. A team built to deliver it.</h2><p className="text-sm text-slate-500 mt-2">The coordinator can assign existing agents or create temporary specialists. Follow their work, evidence and resource use here.</p></div>:<>
          <div className="bg-white rounded-2xl border border-slate-200 p-5"><div className="flex gap-3 items-start justify-between"><h2 className="font-semibold break-words">{current.objective}</h2><span className="shrink-0 text-xs px-2 py-1 bg-slate-100 rounded-full">{label(current.status)}</span></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5">{[['Agents',`${current.nodes.length}/${current.limits.maxAgents}`],['Model calls',`${current.budget.modelCalls}/${current.limits.maxModelCalls}`],['Tool calls',`${current.budget.toolCalls}/${current.limits.maxToolCalls}`],['Search attempts',`${current.budget.searchAttempts}/${current.limits.maxSearchAttempts}`],['Browser steps',`${current.budget.browserSteps||0}/${current.limits.maxBrowserSteps??0}`],['Browser requests',`${current.budget.browserRequests||0}/${current.limits.maxBrowserRequests??0}`]].map(([name,value])=><div key={name} className="bg-slate-50 p-3 rounded-xl"><p className="text-xs text-slate-500">{name}</p><p className="font-mono text-lg mt-1">{value}</p></div>)}</div><p className="text-xs text-slate-500 mt-4">Reported tokens: {current.budget.reportedInputTokens.toLocaleString()} input / {current.budget.reportedOutputTokens.toLocaleString()} output · Unknown usage: {current.budget.unknownUsageCalls} calls</p><p className="text-xs text-slate-500 mt-1">Reserved: {current.budget.reservedInputTokens.toLocaleString()}/{current.limits.maxInputTokens.toLocaleString()} input · {current.budget.reservedOutputTokens.toLocaleString()}/{current.limits.maxOutputTokens.toLocaleString()} output · Deadline {new Date(current.budget.deadline).toLocaleTimeString()}</p>{current.allowedToolIds.includes('tool-browser')&&<p className="text-xs text-slate-600 mt-2">Browser: {current.browserPolicy?.allowActions?'Interactive actions enabled':'Read and navigation'} · {current.browserPolicy?.allowedOrigins.join(', ')}</p>}<div className="flex gap-3 mt-4">{live(current)&&<button onClick={()=>void action('cancel')} className="border border-red-200 text-red-700 rounded-lg px-3 py-2 text-sm flex gap-2 items-center"><Square size={14}/>Stop entire swarm</button>}{current.interrupted&&<button onClick={()=>void action('resume')} className="border rounded-lg px-3 py-2 text-sm">Resume with retained evidence</button>}</div></div>
          {current.approvals?.filter(a=>a.status==='pending').map(a=><section key={a.id} className="border border-amber-300 bg-amber-50 rounded-2xl p-5"><h2 className="font-semibold">Action needs your approval</h2><p className="text-sm">{a.toolId} · expires {new Date(a.expiresAt).toLocaleTimeString()}</p><pre className="text-xs overflow-auto whitespace-pre-wrap my-3">{a.preview}</pre><div className="flex gap-4">{['approved','rejected'].map(decision=><button key={decision} className="border rounded px-3 py-2 text-sm" onClick={()=>void api(`/api/swarm-approvals/${a.id}/decision`,'POST',{decision}).catch(e=>setError(String(e)))}>{decision==='approved'?'Allow this action once':'Deny'}</button>)}</div></section>)}
          {!!current.verification?.length&&<section className="bg-white border rounded-2xl p-5"><h2 className="font-semibold">Deliverable verification</h2>{current.verification.map((v,i)=><p className="text-sm mt-2" key={i}>{v.passed?'✓':'○'} {v.name} · {v.kind} · {v.reason}</p>)}</section>}
          <div className="bg-white rounded-2xl border border-slate-200 p-5"><h2 className="font-semibold mb-4">Execution tree</h2><div className="space-y-3">{treeNodes.map(n=><article key={n.id} style={{marginLeft:Math.min(n.depth??(n.parentId?1:0),4)*16}} className={`border border-slate-200 rounded-xl ${n.parentId?'border-l-4 border-l-amber-200':''}`}><button onClick={()=>setExpanded(expanded===n.id?undefined:n.id)} className="w-full p-4 flex items-center gap-3 text-left"><Bot size={20} className="text-slate-500 shrink-0"/><div className="min-w-0 flex-1"><p className="text-sm font-medium">{n.name} <span className="text-xs font-normal text-slate-400">{!n.parentId?'Coordinator':n.sourceAgentId?'Existing agent':'Temporary specialist'}</span></p><p className="text-xs text-slate-500 truncate">{n.objective}</p></div><span className="text-xs shrink-0">{label(n.status)}</span><ChevronRight size={14}/></button>{expanded===n.id&&<div className="border-t p-4 space-y-3 text-sm"><p>{n.role} · {n.calls} calls · Depth {n.depth??(n.parentId?1:0)}</p><p className="text-xs text-slate-500">Tools: {n.toolIds.map(t=>toolNames[t]||t).join(', ')||'None'}</p><p className="whitespace-pre-wrap">{n.result||'No result yet.'}</p><details><summary className="cursor-pointer text-xs">Instructions and acceptance criteria</summary><p className="whitespace-pre-wrap mt-2">{n.instructions}</p><ul className="list-disc ml-5">{n.acceptanceCriteria.map((c,i)=><li key={i}>{c}</li>)}</ul></details><details><summary className="cursor-pointer text-xs">Execution receipts ({n.receipts.length})</summary><pre className="overflow-auto text-xs bg-slate-50 rounded-lg p-3 mt-2 max-h-96">{JSON.stringify(n.receipts,null,2)}</pre></details></div>}</article>)}</div></div>
          {current.result&&<div className="bg-white border border-slate-200 rounded-2xl p-5"><h2 className="font-semibold flex items-center gap-2 mb-3"><CheckCircle2 size={18}/>{current.status==='completed'?'Deliverable':'Result and limitations'}</h2><p className="whitespace-pre-wrap text-sm leading-relaxed break-words">{current.result}</p><p className="text-xs text-slate-500 mt-4">Completion records execution, not independent verification of factual accuracy.</p></div>}
          <details className="bg-white rounded-2xl border border-slate-200 p-5"><summary className="font-semibold cursor-pointer">Activity log</summary><ol className="mt-3 space-y-2">{current.events.map((e,i)=><li key={i} className="text-xs text-slate-600"><time>{new Date(e.at).toLocaleTimeString()}</time> · {e.type}: {e.detail}</li>)}</ol></details>
        </>}
      </section>
    </div>
  </main>;
}
