import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {SwarmView} from '../swarmTypes';

export function SwarmWorkspace({projectId,current,onError}:{projectId:string;current?:SwarmView;onError:(s:string)=>void}){
 const [files,F]=useState<any[]>([]),[memories,M]=useState<any[]>([]),[skills,S]=useState<any[]>([]),[drafts,Q]=useState<any[]>([]),[routines,R]=useState<any[]>([]),[profiles,P]=useState<any[]>([]),[connectors,C]=useState<any[]>([]);
 const [discovered,D]=useState('');
 const [skillName,N]=useState(''),[skillId,I]=useState(''),[minutes,T]=useState(60),[maxRuns,X]=useState(1),[config,G]=useState('');
 const [reviewing,V]=useState<any>(),[reviewTemplate,E]=useState(''),[reviewParameters,A]=useState(''),[reviewReason,H]=useState(''),[skillParameters,K]=useState('{}');
 const refresh=async()=>{if(!projectId)return;const [f,m,s,q,r,p,c]=await Promise.all([api(`/api/projects/${projectId}/files`),api(`/api/projects/${projectId}/swarm-memory`),api(`/api/projects/${projectId}/skills`),api(`/api/projects/${projectId}/skill-drafts`),api(`/api/projects/${projectId}/routines`),api(`/api/projects/${projectId}/browser-profiles`),api('/api/swarm-connectors')]);F(f);M(m);S(s);Q(q);R(r);P(p);C(c);};
 const act=async(fn:()=>Promise<unknown>)=>{try{await fn();await refresh();}catch(e){onError(String(e));}};
 useEffect(()=>{void act(refresh);const t=setInterval(()=>void act(refresh),5000);return()=>clearInterval(t);},[projectId]);
 const upload=async(file:File)=>{if(file.size>6*1024*1024)throw new Error('Maximum upload is 6 MiB');const data=await file.arrayBuffer();let binary='';for(const b of new Uint8Array(data))binary+=String.fromCharCode(b);await api(`/api/projects/${projectId}/files`,'POST',{name:file.name,base64:btoa(binary),expectedVersion:files.find(f=>f.name===file.name)?.version||0});};
 const captureSkill=async()=>{if(!current)throw new Error('Select a run first');await api('/api/swarm-skill-drafts','POST',{name:skillName,runId:current.id});N('');};
 const inspectDraft=(draft:any)=>{V(draft);E(JSON.stringify(draft.template,null,2));A(JSON.stringify(draft.parameters,null,2));H('');};
 const reviewDraft=async(decision:'approved'|'rejected')=>{if(!reviewing)throw new Error('Select a draft first');await api(`/api/swarm-skill-drafts/${reviewing.id}/review`,'POST',{decision,reason:reviewReason,...(decision==='approved'?{template:JSON.parse(reviewTemplate),parameters:JSON.parse(reviewParameters)}:{})});V(undefined);};
 return <section aria-label="Persistent project workspace" className="bg-white rounded-2xl border p-5 space-y-5">
 <h2 className="font-semibold">Project workspace</h2>
 <div><h3 className="text-sm font-medium">Files and deliverables</h3><label className="block text-xs my-2">Upload file (up to 6 MiB)<input aria-label="Upload project file" type="file" className="block mt-2" onChange={e=>{const f=e.target.files?.[0];if(f)void act(()=>upload(f));e.target.value='';}}/></label>{files.map(f=><div key={f.id} className="text-xs py-2 flex justify-between gap-2"><a className="underline break-all" href={`/api/projects/${projectId}/files/download?name=${encodeURIComponent(f.name)}&version=${f.version}`}>{f.name}</a><span>v{f.version} · {f.bytes} bytes</span></div>)}</div>
 <details><summary className="text-sm cursor-pointer">Memory proposals ({memories.filter(m=>m.status==='proposed').length})</summary>{memories.map(m=><article key={m.id} className="text-xs border rounded p-3 mt-2"><p>{m.content}</p><p className="text-slate-500 mt-1">{m.status} · source run {m.sourceRunId}</p>{m.status==='proposed'&&<div className="flex gap-3 mt-2">{['approved','rejected'].map(decision=><button className="underline" key={decision} onClick={()=>void act(()=>api(`/api/swarm-memory/${m.id}/decision`,'POST',{decision}))}>{decision==='approved'?'Approve memory':'Reject'}</button>)}</div>}</article>)}</details>
 <details><summary className="text-sm cursor-pointer">Reviewed skills and scheduled routines</summary><p className="text-xs text-slate-500 my-2">Capture only a completed run. Inspect the frozen authority, declared inputs and sanitized trace before approval. Parameters can change task text, never tools, connectors, limits or approval boundaries. Every approved edit and rollback creates a new immutable version.</p><div className="flex gap-2"><input aria-label="Skill name" className="border rounded p-2 min-w-0 text-xs" value={skillName} onChange={e=>N(e.target.value)} placeholder="Skill name"/><button disabled={current?.status!=='completed'||!skillName.trim()} className="text-xs underline disabled:opacity-40" onClick={()=>void act(captureSkill)}>Capture completed run for review</button></div>
 {drafts.map(d=><article key={d.id} className="text-xs border rounded p-2 mt-2"><p>{d.name} · {d.status} · trace {d.traceDigest.slice(0,12)}</p>{d.redactionPaths.length>0&&<p className="text-red-700">Redacted fields require replacement: {d.redactionPaths.join(', ')}</p>}{d.status==='draft'&&<button className="underline" onClick={()=>inspectDraft(d)}>Inspect and review</button>}</article>)}
 {reviewing&&<section aria-label="Skill draft review" className="border rounded p-3 mt-2 space-y-2"><p className="font-medium">Review {reviewing.name}</p><label className="block">Frozen template<textarea aria-label="Reviewed skill template" rows={8} className="border rounded p-2 w-full font-mono" value={reviewTemplate} onChange={e=>E(e.target.value)}/></label><label className="block">Declared parameters<textarea aria-label="Reviewed skill parameters" rows={5} className="border rounded p-2 w-full font-mono" value={reviewParameters} onChange={e=>A(e.target.value)}/></label><label className="block">Review reason<input aria-label="Skill review reason" className="border rounded p-2 w-full" value={reviewReason} onChange={e=>H(e.target.value)}/></label><div className="flex gap-3"><button disabled={!reviewReason.trim()} className="underline disabled:opacity-40" onClick={()=>void act(()=>reviewDraft('approved'))}>Approve immutable skill</button><button disabled={!reviewReason.trim()} className="underline disabled:opacity-40" onClick={()=>void act(()=>reviewDraft('rejected'))}>Reject draft</button></div></section>}
 <select aria-label="Routine skill" className="border rounded p-2 text-xs w-full my-2" value={skillId} onChange={e=>I(e.target.value)}><option value="">Choose pinned skill version</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name} v{s.version}</option>)}</select>{skills.filter(s=>s.id===skillId).map(s=><div key={s.id} className="text-xs border rounded p-2"><p>Declared inputs: {(s.parameters||[]).map((p:any)=>p.name).join(', ')||'none'}</p>{s.diff&&<p>Diff from v{s.diff.fromVersion}: {s.diff.changedPaths.join(', ')||'parameter definitions only'}</p>}{s.version>1&&<button className="underline" onClick={()=>void act(()=>api(`/api/swarm-skills/${s.id}/rollback`,'POST',{toVersion:s.version-1,reason:'Owner selected previous reviewed version.'}))}>Roll back to v{s.version-1} as a new version</button>}</div>)}
 <label className="block text-xs my-2">Skill input JSON<textarea aria-label="Skill parameters" className="border rounded p-2 w-full font-mono" rows={3} value={skillParameters} onChange={e=>K(e.target.value)}/></label><button disabled={!skillId} className="text-xs underline mr-4 disabled:opacity-40" onClick={()=>void act(()=>api(`/api/swarm-skills/${skillId}/replay`,'POST',JSON.parse(skillParameters)))}>Run reviewed skill now</button>
 <div className="flex gap-2 text-xs mt-2"><label>Interval (minutes)<input type="number" min={1} className="border rounded p-2 w-full" value={minutes} onChange={e=>T(+e.target.value)}/></label><label>Maximum runs<input type="number" min={1} max={100} className="border rounded p-2 w-full" value={maxRuns} onChange={e=>X(+e.target.value)}/></label></div><button disabled={!skillId} className="text-xs underline my-2" onClick={()=>void act(()=>api('/api/swarm-routines','POST',{skillId,parameters:JSON.parse(skillParameters),intervalMinutes:minutes,maxRuns,startsAt:new Date().toISOString()}))}>Authorize routine, starting now</button>{routines.map(r=><div key={r.id} className="text-xs border rounded p-2 mt-1">{skills.find(s=>s.id===r.skillId)?.name} · {r.status} · {r.runs}/{r.maxRuns} runs {r.status==='active'&&<button className="underline ml-2" onClick={()=>void act(()=>api(`/api/swarm-routines/${r.id}/pause`,'POST',{}))}>Pause</button>}{r.error&&<p>{r.error}</p>}</div>)}</details>
 <details><summary className="text-sm cursor-pointer">Saved browser sessions</summary><p className="text-xs my-2">Sessions are private to this project, expire after seven idle days and allow one active user at a time.</p>{profiles.map(p=><div className="text-xs flex justify-between py-2" key={p.profileId}>{p.profileId}<button className="underline" onClick={()=>void act(()=>api(`/api/projects/${projectId}/browser-profiles/${p.profileId}`,'DELETE'))}>Delete saved session</button></div>)}</details>
 <details><summary className="text-sm cursor-pointer">Approved connector gateway</summary><p className="text-xs my-2">Configure an MCP Streamable HTTP connector with protocol: "mcp", or a legacy JSON-RPC gateway. Credentials are server environment variables; never put secrets in this form. Discovery lists tools; it never grants access automatically. MCP currently supports bounded HTTP tool sessions; OAuth and local stdio servers are not enabled.</p>{connectors.map(c=><div className="text-xs border rounded p-2 my-2" key={c.id}><p>{c.name} · {c.enabled?'enabled':'disabled'}</p><p className="break-all">ID: {c.id}</p>{c.enabled&&c.protocol==='mcp'&&<button className="underline mr-3" onClick={()=>void act(async()=>{const d=await api(`/api/swarm-connectors/${c.id}/discover`,'POST',{});D(JSON.stringify(d,null,2));})}>Discover tools</button>}{c.enabled&&<button className="underline" onClick={()=>void act(()=>api(`/api/swarm-connectors/${c.id}/disable`,'POST',{}))}>Disable</button>}</div>)}{discovered&&<pre aria-label="Discovered MCP tools" className="text-xs max-h-64 overflow-auto whitespace-pre-wrap break-all">{discovered}</pre>}<textarea aria-label="Connector configuration" className="border rounded p-2 w-full text-xs" rows={5} value={config} onChange={e=>G(e.target.value)} placeholder={'{"name":"My gateway","endpoint":"https://gateway.example/tools","tools":[{"name":"lookup","effect":"read"}]}'} /><button disabled={!config} className="text-xs underline" onClick={()=>void act(()=>api('/api/swarm-connectors','POST',JSON.parse(config)))}>Approve connector configuration</button></details>
 </section>;
}
