import 'dotenv/config';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createHash,randomUUID} from 'node:crypto';
import {Store} from '../src/server/store';import {Workspace} from '../src/server/workspace';import {SwarmEngine} from '../src/server/swarm';
import {INITIAL_AGENTS} from '../src/data/initialData';import {infer,defaultSettings} from '../src/server/providers';
import {reserveRequest,remainingRequestBudget} from '../src/server/operations';
import {semanticReviewSchema,reviewPacket,reviewToolFor,reviewTool,validateReview} from '../src/server/semanticReview';
import {reviewerChallenges,reconciliationInputs,reconciliationExpected,reconciliationObjective} from './evaluation/priority-one-corpus';
const sha=(s:string|Buffer)=>createHash('sha256').update(s).digest('hex');
function sourceIdentity(){const files:string[]=[];const visit=(d:string)=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())visit(f);else files.push(f);}};for(const d of ['src','scripts','sandbox'])visit(d);files.push('server.ts','package.json','package-lock.json');return sha(files.sort().map(f=>f+':'+sha(fs.readFileSync(f))).join('\n'));}
const [mode,filename]=process.argv.slice(2);if(!['--prepare','--run'].includes(mode)||!filename)throw new Error('Usage: --prepare new-manifest.json OR --run manifest.json');
const manifestPath=path.resolve(filename),model='qwen3.5:9b';
const declaration={model,temperature:0,reviewerCases:reviewerChallenges,repetitions:1,reviewerThresholds:{maxFalseAcceptances:0,minTrueAcceptances:3,maxErrors:0},arms:['single','swarm'],armMaxModelCalls:14,maximumCampaignModelCalls:36,objective:reconciliationObjective,inputs:reconciliationInputs,expected:reconciliationExpected,limits:{maxAgents:3,maxDepth:1,concurrency:2,maxModelCalls:14,maxCallsPerAgent:14,maxToolCalls:16,maxSearchAttempts:0,maxMinutes:10,maxInputTokens:250000,maxOutputTokens:30000,maxTokensPerCall:1536},scope:'Developer-authored held-out challenge pilot and one paired task, NOT independent external holdout, general reliability, causal speedup or full VAC-23/28/42 qualification. No correction/tuning/retry after observing results.',costPolicy:'No paid inference/search; monetary cost and human correction time unknown, not zero. All attempts use existing shared daily ledger.'};
if(mode==='--prepare'){
 if(fs.existsSync(manifestPath))throw new Error('Manifest already exists');fs.mkdirSync(path.dirname(manifestPath),{recursive:true});fs.writeFileSync(manifestPath,JSON.stringify({createdAt:new Date().toISOString(),sourceHash:sourceIdentity(),declarationHash:sha(JSON.stringify(declaration)),declaration},null,2),{flag:'wx'});console.log('Frozen declaration: '+manifestPath);process.exit(0);
}
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));const assertFrozen=()=>{if(manifest.sourceHash!==sourceIdentity()||manifest.declarationHash!==sha(JSON.stringify(declaration)))throw new Error('Frozen candidate/declaration changed; preserve this campaign and prepare a new one');};assertFrozen();
const output=manifestPath.replace(/\.json$/,'')+'-results.json';if(fs.existsSync(output))throw new Error('Results already exist; do not rerun a consumed challenge');
const budgets=new Store(path.resolve('data'));const admission=remainingRequestBudget(budgets,'inference');
const report:any={manifestSha256:sha(fs.readFileSync(manifestPath)),sourceHash:manifest.sourceHash,declarationHash:manifest.declarationHash,startedAt:new Date().toISOString(),admission,reviewer:[],arms:[],status:'preflight',campaignProviderCalls:0};
const save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));save();
try{
 if(admission.remaining!==null&&admission.remaining<declaration.maximumCampaignModelCalls)throw new Error('Insufficient daily allowance for the frozen worst-case campaign; no provider calls sent');
 const response=await fetch('http://127.0.0.1:11434/api/tags',{signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('Ollama discovery failed');const tags:any=await response.json();const identity=tags.models?.find((m:any)=>m.name===model);if(!identity?.digest)throw new Error('Pinned model unavailable');report.modelIdentity={name:model,digest:identity.digest,details:identity.details};
 const guardedInfer:typeof infer=async(...args)=>{if(report.campaignProviderCalls>=36)throw new Error('Campaign provider-call cap reached');report.campaignProviderCalls++;save();return infer(...args);};
 report.status='running';save();
 for(const c of reviewerChallenges){
  assertFrozen();const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vac-p1-review-')),store=new Store(dir,budgets),workspace=new Workspace(store);const row:any={id:c.id,expected:c.expected,startedAt:new Date().toISOString()};const started=Date.now();
  try{
   store.put('projects','p',{id:'p',workspaceId:'ws-default'});workspace.write('p','source.txt',Buffer.from(c.source),0,'owner');workspace.write('p','report.txt',Buffer.from(c.report),0,'producer','run');
   const policy=semanticReviewSchema.parse({reviewerId:'reviewer',criteria:[c.criterion],inputNames:['source.txt'],outputNames:['report.txt']});const packet=reviewPacket(workspace,{id:'run',projectId:'p',objective:'Review source support.',semanticReview:policy}as any,'Check the report.');row.packetHash=packet.packetHash;
   reserveRequest(store,'inference');const r=await guardedInfer({provider:'ollama',model,endpoint:'http://127.0.0.1:11434',temperature:0,maxTokens:1536,allowFinal:false},packet.messages,AbortSignal.timeout(90000),[reviewToolFor(policy,packet.files)]);row.receipt=r.receipt;if(r.decision.action!=='tool'||r.decision.toolId!==reviewTool.id)throw new Error('No structured review');row.review=validateReview(r.decision.parameters,policy,packet.files);row.correct=row.review.passed===c.expected;
  }catch(e){row.error=e instanceof Error?e.message:String(e);row.correct=false;}finally{row.durationMs=Date.now()-started;report.reviewer.push(row);save();store.close();}
  console.log(JSON.stringify({challenge:row.id,correct:row.correct,accepted:row.review?.passed,error:row.error}));
 }
 for(const arm of declaration.arms){
  assertFrozen();const directory=fs.mkdtempSync(path.join(os.tmpdir(),'vac-p1-'+arm+'-')),store=new Store(directory,budgets);const tools=['tool-files','tool-calculator','tool-write-file'];
  const agent={...structuredClone(INITIAL_AGENTS[0]),id:'manager',workspaceId:'ws-default',displayName:'Coordinator',autonomyLevel:3,toolIds:tools,llmConfig:{provider:'ollama',model,temperature:0,maxTokens:1536}};
  store.put('agents','manager',agent);store.put('agents','reviewer',{...agent,id:'reviewer',displayName:'Reviewer',toolIds:[]});store.put('projects','p',{id:'p',workspaceId:'ws-default',name:'Synthetic invoice reconciliation',members:[]});
  const engine=new SwarmEngine(store,()=>defaultSettings,guardedInfer);const started=Date.now();const result:any={arm,directory,startedAt:new Date().toISOString(),humanCorrectionMinutes:null,monetaryCost:null};report.arms.push(result);
  try{
   for(const [name,body]of Object.entries(reconciliationInputs))engine.workspace.write('p',name,Buffer.from(body),0,'owner');
   const semanticReview={reviewerId:'reviewer',criteria:['All result totals, currency and units follow the source invoices minus credits, with identical duplicate IDs counted once and disclosed.'],inputNames:Object.keys(reconciliationInputs),outputNames:['result.json']};
   const instruction=arm==='single'?' Solve the task yourself without delegation.': ' Use exactly two direct specialists, North for north.txt and South for south.txt. Each reads its assigned file, uses calculator and returns net cents and duplicate IDs in its final reply, without writing any file. Their tasks are independent. The coordinator combines their evidence, personally calculates the combined total and writes result.json. No supervisor nodes, peer messages, extra tasks or duplicated calculations.';
   let run=engine.create({coordinatorId:'manager',projectId:'p',objective:reconciliationObjective+instruction,mode:'dynamic',...(arm==='swarm'?{harness:'deepagents'}:{}),allowedToolIds:tools,requiredToolIds:arm==='single'?tools:['tool-calculator','tool-write-file'],contracts:[{name:'result.json',kind:'exists'}],semanticReview,limits:{...declaration.limits,maxAgents:arm==='single'?1:3}},'p1-'+randomUUID());
   result.run=run;save();
   for(let i=0;i<150&&['queued','working','waiting_children'].includes(run.status);i++){await engine.tick();run=engine.get(run.id);result.run=run;save();console.log(JSON.stringify({arm,status:run.status,calls:run.budget.modelCalls,nodes:run.nodes.map(n=>({name:n.name,status:n.status,calls:n.calls}))}));}
   if(['queued','working','waiting_children'].includes(run.status)){run=engine.cancel(run.id);result.error='Tick bound reached';}
   result.run=run;let actual:any;try{const f=engine.workspace.file('p','result.json');actual=JSON.parse(Buffer.from(f.base64,'base64').toString());result.artifact={sha256:f.sha256,runId:f.runId,version:f.version,content:actual};}catch{}
   result.checks={completed:run.status==='completed',currentArtifact:result.artifact?.runId===run.id&&result.artifact?.version===1,exactContent:!!actual&&Object.keys(actual).sort().join()===Object.keys(reconciliationExpected).sort().join()&&Object.entries(reconciliationExpected).every(([k,v])=>JSON.stringify(actual[k])===JSON.stringify(v)),semanticAccepted:run.semanticReviewResult?.passed===true,topology:arm==='single'?run.nodes.length===1:run.nodes.length===3&&run.nodes.slice(1).every(n=>n.depth===1),calculatorEvidence:run.nodes.some(n=>n.receipts.some(r=>r.toolId==='tool-calculator'&&r.status==='succeeded'))};result.passed=Object.values(result.checks).every(Boolean);
  }catch(e){result.error=e instanceof Error?e.message:String(e);result.passed=false;}finally{result.durationMs=Date.now()-started;engine.stop();store.close();save();}
 }
 assertFrozen();const endTags:any=await(await fetch('http://127.0.0.1:11434/api/tags')).json();if(endTags.models.find((m:any)=>m.name===model)?.digest!==report.modelIdentity.digest)throw new Error('Model identity changed during campaign');
 report.reviewerSummary={falseAcceptances:report.reviewer.filter((r:any)=>!r.expected&&r.review?.passed).length,trueAcceptances:report.reviewer.filter((r:any)=>r.expected&&r.review?.passed).length,errors:report.reviewer.filter((r:any)=>r.error).length};const q=report.reviewerSummary;q.passed=q.falseAcceptances===0&&q.trueAcceptances>=3&&q.errors===0;
 report.comparison={pairedTasks:1,armsPassed:report.arms.filter((r:any)=>r.passed).length,advantage:'NOT_ESTABLISHED',reason:'One fixed-order synthetic task cannot establish general usefulness or causal speedup; no measured owner correction time. These results determine what to qualify next.',scopeConfounders:'Same inputs/model/tools/root budgets; execution strategy differs. Swarm includes planner overhead and two specialists. Local Ollama scheduling/caching and fixed order affect timings. Golden answers were checked only after execution, not exposed as runtime contracts.'};report.status='finished';report.completedAt=new Date().toISOString();report.budgetAfter=remainingRequestBudget(budgets,'inference');save();console.log(JSON.stringify({reviewer:report.reviewerSummary,arms:report.arms.map((r:any)=>({arm:r.arm,passed:r.passed,calls:r.run?.budget.modelCalls,durationMs:r.durationMs})),comparison:report.comparison,budget:report.budgetAfter}));
}catch(e){report.status='blocked';report.error=e instanceof Error?e.message:String(e);report.budgetAfter=remainingRequestBudget(budgets,'inference');save();throw e;}finally{budgets.close();}
