import {createHash} from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import http from 'node:http';
import {Store} from '../src/server/store';import {SwarmEngine,SWARM_TOOL_IDS,SPAWN_TOOL} from '../src/server/swarm';import {Routines} from '../src/server/routines';import {INITIAL_AGENTS} from '../src/data/initialData';import {defaultSettings,infer} from '../src/server/providers';
const mode=process.argv[2]||'scripted',output=path.resolve(process.argv[3]||'workspace-evaluation.json');if(fs.existsSync(output))throw new Error('Use a new evidence filename');
const evaluationModel=process.argv[4]||'qwen3.5:9b';
const sourceFiles:string[]=[];const visit=(dir:string)=>{for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())visit(file);else if(entry.isFile())sourceFiles.push(file);}};
for(const dir of ['src','scripts','sandbox'])visit(dir);sourceFiles.push('server.ts','package.json','package-lock.json','index.html','vite.config.ts','tsconfig.json');
const sha=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
const evaluatedSourceHash=sha(sourceFiles.sort().map(file=>file+':'+sha(fs.readFileSync(file))).join('\n'));

const directory=fs.mkdtempSync(path.join(os.tmpdir(),'vac-capabilities-')),store=new Store(directory);const published:any[]=[];
const connector=http.createServer(async(req,res)=>{let body='';for await(const b of req)body+=b;const x=JSON.parse(body);published.push(x.params);res.setHeader('content-type','application/json');res.end(JSON.stringify({jsonrpc:'2.0',id:x.id,result:{content:[{type:'text',text:'Saved test sales summary'}]}}));});
await new Promise<void>(r=>connector.listen(0,'127.0.0.1',r));const endpoint=`http://127.0.0.1:${(connector.address()as any).port}/tools`;process.env.VAC_CONNECTOR_LOCAL_ENDPOINTS=endpoint;
const realFetch=globalThis.fetch;if(mode==='scripted')globalThis.fetch=(async(input:any,init:any)=>String(input).startsWith('https://api.duckduckgo.com')?new Response(JSON.stringify({Heading:'Example Domain',AbstractURL:'https://example.com',AbstractText:'Deterministic search fixture: example domains are for documentation.'})):realFetch(input,init))as any;
store.put('settings','search',{activeProvider:'duckduckgo'});
const manager={...structuredClone(INITIAL_AGENTS[0]),id:'manager',workspaceId:'ws-default',displayName:'Coordinator',autonomyLevel:3,primaryResponsibility:'Coordinate evidence-based sales reporting.',toolIds:[...SWARM_TOOL_IDS],llmConfig:{provider:'ollama',model:mode.startsWith('live')?evaluationModel:'scripted-fixture',temperature:0,maxTokens:2048}};
store.put('agents','manager',manager);store.put('agents','saved-researcher',{...manager,id:'saved-researcher',displayName:'Saved Researcher',toolIds:['tool-web-search','tool-browser']});store.put('projects','project',{id:'project',workspaceId:'ws-default',name:'Sales review acceptance',description:'Synthetic sales data only',members:[]});
const code=`import csv,json\nfrom docx import Document\nfrom openpyxl import Workbook\nfrom pptx import Presentation\nfrom reportlab.pdfgen import canvas\nrows=list(csv.DictReader(open('sales.csv')))\nrevenue=sum(int(r['revenue']) for r in rows)\ncost=sum(int(r['cost']) for r in rows)\ndata={'revenue':revenue,'cost':cost,'profit':revenue-cost,'rows':len(rows)}\nopen('summary.json','w').write(json.dumps(data))\nd=Document();d.add_heading('Sales review',0);d.add_paragraph(str(data));d.save('report.docx')\nw=Workbook();w.active.append(list(data));w.active.append(list(data.values()));w.save('report.xlsx')\np=Presentation();p.slides.add_slide(p.slide_layouts[0]).shapes.title.text='Sales revenue '+str(revenue);p.save('report.pptx')\nc=canvas.Canvas('report.pdf');c.drawString(72,700,str(data));c.save()\nprint(json.dumps(data))`;
const worker=(name:string,tools:string[],extra:any={})=>({name,role:'Sales specialist',instructions:'Use assigned tools and return verified evidence.',objective:'Sales task '+name,toolIds:tools,requiredToolIds:tools,acceptanceCriteria:['Return source-backed results.'],...extra});
const steps=new Map<string,number>();let c:any;
const scripted=async(_p:any,m:any[])=>{const system=m[0].content,name=system.match(/^You are ([^,]+)/)?.[1],i=steps.get(name)||0;steps.set(name,i+1);const state=JSON.parse([...m].reverse().find(x=>x.content.startsWith('RUN STATE')).content.split('RUN STATE (server supplied): ')[1]);const tool=(toolId:string,parameters:any)=>({action:'tool',toolId,parameters});const final={action:'final',reply:'Verified revenue 600, cost 360, profit 240. Five generated report files, source evidence, peer review and connector draft retained.'};let d:any;
if(name==='Coordinator'){const choices=[()=>tool(SPAWN_TOOL,{workers:[worker('TeamLead',['tool-code'])]}),()=>tool(SPAWN_TOOL,{workers:[worker('Researcher',['tool-web-search','tool-browser'],{agentId:'saved-researcher'}),worker('Reviewer',['tool-files','tool-evidence','tool-peer'],{dependsOn:['Researcher']})]}),()=>tool('tool-select-tools',{toolIds:['tool-read-project','tool-calculator','tool-memory']}),()=>tool('tool-read-project',{}),()=>tool('tool-calculator',{operation:'subtract',a:600,b:360}),()=>tool('tool-memory',{propose:'Synthetic sales example uses integer USD values.'}),()=>tool('tool-select-tools',{toolIds:['tool-write-file','tool-connector']}),()=>tool('tool-write-file',{name:'review.md',content:'Revenue 600; cost 360; profit 240. Example domain is a documentation source, not sales evidence.',expectedVersion:0}),()=>tool('tool-connector',{connectorId:c.id,tool:'save_draft',arguments:{revenue:600,profit:240}}),()=>final];d=choices[i]?.()||final;}
else if(name==='TeamLead')d=i===0?tool(SPAWN_TOOL,{workers:[worker('Compute',['tool-code'])]}):final;
else if(name==='Compute')d=i===0?tool('tool-code',{language:'python',code,inputNames:['sales.csv']}):final;
else if(name==='Researcher')d=i===0?tool('tool-web-search',{query:'Example domain'}):i===1?tool('tool-browser',{action:'navigate',url:'https://example.com'}):final;
else if(name==='Reviewer')d=i===0?tool('tool-files',{name:'summary.json'}):i===1?tool('tool-evidence',{nodeId:state.nodes.find((n:any)=>n.name==='Compute').id}):i===2?tool('tool-peer',{nodeId:state.nodes.find((n:any)=>!n.parentId).id,message:'Reviewed summary: revenue 600, cost 360, profit 240.'}):final;
else d=final;return{decision:d,receipt:{provider:'ollama',model:'scripted-fixture',inputTokens:10,outputTokens:10,cost:null}};};
const engine=new SwarmEngine(store,()=>defaultSettings,mode.startsWith('live')?infer:scripted as any);c=engine.workspace.saveConnector({name:'Local acceptance fixture',endpoint,tools:[{name:'save_draft',effect:'write',inputSchema:{type:'object',properties:{revenue:{type:'number'},profit:{type:'number'}},required:['revenue','profit'],additionalProperties:false}}]});engine.workspace.write('project','sales.csv',Buffer.from('product,revenue,cost\nA,100,60\nB,200,120\nC,300,180\n'),0,'owner');
const objective=`Create a sales review from sales.csv. Its columns are product,revenue,cost. Use tool-code recipe=tabular_report, inputName=sales.csv, valueColumns=[revenue,cost], outputPrefix=report to generate all five documents deterministically. Revenue must be computed from the file, not guessed. Produce summary.json with numeric revenue,cost,profit,rows, plus report.docx,report.xlsx,report.pptx,report.pdf and review.md. Use sandbox Python document libraries. Delegate through a TeamLead to a Compute grandchild first. Then use saved-researcher for web search "Example domain" and read https://example.com; this web source explains documentation domains, not sales data. Record empty search results honestly; reading Example Domain is sufficient for this documentation-source task, never invent external sales evidence. A separate Reviewer must depend on Researcher, read summary.json, inspect Compute evidence with tool-evidence and message the coordinator with tool-peer. The coordinator must read project metadata, independently calculate 600-360 with calculator, propose a project memory, write review.md, and call connector ${c.id} tool save_draft with computed revenue/profit. Select a small working tool set when needed. The local test connector write will be approved once after its exact arguments are checked. Avoid duplicate work; use existing artifacts. Finish only after contracts pass.`;
const contracts=[{name:'summary.json',kind:'json_equals',path:['revenue'],expected:600},{name:'summary.json',kind:'json_equals',path:['profit'],expected:240},...['report.docx','report.xlsx','report.pptx','report.pdf','review.md'].map(name=>({name,kind:'exists'}))];
const template={harness:mode==='live-harness'?'deepagents':'native',coordinatorId:'manager',projectId:'project',objective,mode:'hybrid',allowedToolIds:[...SWARM_TOOL_IDS],requiredToolIds:['tool-read-project','tool-calculator','tool-memory','tool-write-file','tool-connector'],requiredDepth:2,browserPolicy:{allowedOrigins:['https://example.com'],allowActions:false,profileId:'sales-research'},connectorIds:[c.id],contracts,limits:{maxAgents:7,concurrency:2,maxDepth:2,maxModelCalls:64,maxCallsPerAgent:24,maxInputTokens:750000,maxOutputTokens:100000,maxTokensPerCall:2048,maxToolCalls:50,maxSearchAttempts:4,maxSandboxRuns:5,maxMinutes:20}};
const plan=mode==='live-planned'?[
 {...worker('TeamLead',['tool-code']),key:'lead',requiredToolIds:[],instructions:'Wait for Compute and then summarize its verified totals. Do not run code yourself or create extra workers.',objective:'Summarize the existing Compute child result.'},
 {...worker('Compute',['tool-code']),key:'compute',parentKey:'lead',toolSequence:['tool-code'],instructions:'Run the built-in tabular_report recipe once using sales.csv, valueColumns revenue and cost, outputPrefix report. Then finalize with computed values. Do not generate custom code or repeat successful work.',objective:'Generate the five report artifacts from sales.csv using the deterministic recipe.'},
 {...worker('Researcher',['tool-web-search','tool-browser']),key:'research',toolSequence:['tool-web-search','tool-browser'],agentId:'saved-researcher',requiredToolIds:['tool-browser'],instructions:'Search exactly Example domain once. Then navigate https://example.com. Record empty search honestly; the task is documentation-domain verification, not external sales research. Finalize after reading the page.',objective:'Verify that example.com is a documentation domain. Search may be empty; browser page is the primary source.'},
 {...worker('Reviewer',['tool-files','tool-evidence','tool-peer']),key:'review',toolSequence:['tool-files','tool-evidence','tool-peer'],dependsOn:['lead','research'],instructions:'Read summary.json using tool-files; read Compute node evidence using its RUN STATE ID; send the coordinator a tool-peer message with the verified totals. Then finalize. Never rewrite files.',objective:'Review totals 600 revenue, 360 cost and 240 profit against Compute evidence and notify the coordinator.'}
]:[];
const toolSequence=mode==='live-planned'?['tool-read-project','tool-calculator','tool-memory','tool-write-file','tool-connector']:[];
const started=Date.now();let result=engine.create({...template,plan,toolSequence},'evaluation-'+crypto.randomUUID());let last='';const report:any={sourceHash:evaluatedSourceHash,mode,model:manager.llmConfig.model,inferenceSettings:{temperature:0,think:false,numCtx:16384,maxTokens:2048},limits:template.limits,limitations:mode==='scripted'?['Scripted decisions test orchestration and tools, not autonomous reasoning.','Search response is a deterministic fixture; browser and Docker execute for real.']:[mode==='live-harness'?'Deep Agents generates the workflow through budgeted local Ollama; VAC executes it. No owner-supplied plan.':mode==='live-planned'?'Owner-supplied workflow plan; real Ollama decisions execute each task. This does not prove autonomous planning.':'Live autonomous local Ollama decisions; no claim of broad product parity.'],startedAt:new Date().toISOString(),directory};
const persist=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));
try{
for(let i=0;i<200&&['queued','working','waiting_children','waiting_approval'].includes(result.status);i++){
 await engine.tick();result=engine.get(result.id);const state=result.nodes.map(n=>`${n.name}:${n.status}:${n.calls}`).join(' | ');if(state!==last){console.log(state);last=state;report.run=result;persist();}
 if(mode.startsWith('live')&&result.nodes.some(n=>['failed','budget_exhausted','blocked','partial'].includes(n.status))){report.earlyStop='A required workflow node failed; stop this qualification trial and retain evidence.';result=engine.cancel(result.id);break;}
 for(const a of result.approvals||[])if(a.status==='pending'){
  const parameters=JSON.parse(a.preview).parameters;const valid=published.length===0&&a.toolId==='tool-connector'&&parameters.connectorId===c.id&&parameters.tool==='save_draft'&&parameters.arguments?.revenue===600&&parameters.arguments?.profit===240;
  engine.decideApproval(a.id,valid?'approved':'rejected');console.log('Fixture approval',valid);result=engine.get(result.id);
 }
}
const memory=engine.workspace.memories('project')[0];if(memory)engine.workspace.decideMemory(memory.id,'approved');
const scheduler=new Routines(engine);const skill=scheduler.saveSkill({name:'Sales review',template:{...template,plan,toolSequence}});const routine=scheduler.create({skillId:skill.id,intervalMinutes:60,maxRuns:1,startsAt:new Date(Date.now()+3600000).toISOString()});scheduler.pause(routine.id);
const files=engine.workspace.files('project');const receipts=result.nodes.flatMap(n=>n.receipts);const checks={completed:result.status==='completed',contracts:result.verification?.every(v=>v.passed),allRegistryTools:SWARM_TOOL_IDS.every(t=>receipts.some(r=>r.toolId===t&&r.status==='succeeded')),recursive:result.nodes.some(n=>n.depth===2&&n.status==='completed'),savedAgent:result.nodes.some(n=>n.sourceAgentId==='saved-researcher'&&n.status==='completed'),dependency:result.nodes.some(n=>n.dependencies?.length&&n.status==='completed'),peerMessage:store.all('swarm-messages').length>0,approvedMemory:engine.workspace.memories('project').some(m=>m.status==='approved'),browserProfile:engine.browserProfiles('project').length>0,exactConnectorWrite:published.length===1&&published[0].arguments.revenue===600&&published[0].arguments.profit===240,skillVersion:skill.version===1,routinePaused:scheduler.list('project')[0].status==='paused'};
report.run=result;report.checks=checks;report.passed=Object.values(checks).every(Boolean);report.durationSeconds=(Date.now()-started)/1000;report.artifacts=files;report.connectorWrites=published;persist();const dest=output.replace(/\.json$/,'-files');fs.mkdirSync(dest,{recursive:true});for(const f of files)fs.writeFileSync(path.join(dest,f.name),Buffer.from(engine.workspace.file('project',f.name).base64,'base64'));console.log(JSON.stringify({passed:report.passed,checks,durationSeconds:report.durationSeconds}));if(!report.passed)process.exitCode=1;
}finally{engine.stop();await new Promise<void>(r=>connector.close(()=>r()));store.close();globalThis.fetch=realFetch;}
