import 'dotenv/config';
import fs from 'node:fs';import path from 'node:path';import {createHash,randomUUID} from 'node:crypto';
import {Store} from '../src/server/store';import {SwarmEngine,isSwarmLive} from '../src/server/swarm';import {INITIAL_AGENTS} from '../src/data/initialData';import {infer,defaultSettings} from '../src/server/providers';import {remainingRequestBudget} from '../src/server/operations';import {changeLogCases} from './evaluation/change-log-corpus';
const sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
function identity(){const files:string[]=[];for(const dir of ['src','scripts']){const visit=(d:string)=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())visit(p);else files.push(p);}};visit(dir);}files.push('package.json','package-lock.json');return sha(files.sort().map(f=>f+':'+sha(fs.readFileSync(f))).join('\n'));}
const [mode,file]=process.argv.slice(2);if(!['--prepare','--run'].includes(mode)||!file?.endsWith('.json'))throw Error('Use --prepare/--run manifest.json');
const model='qwen3.5:9b',endpoint='http://127.0.0.1:11434',cases=changeLogCases();
async function modelIdentity(){const res=await fetch(endpoint+'/api/tags',{signal:AbortSignal.timeout(5000)});if(!res.ok)throw Error('Discovery failed');const d:any=await res.json();const m=d.models.find((m:any)=>m.name===model);if(!m?.digest)throw Error('Model unavailable');return {name:model,digest:m.digest};}
const limits={maxAgents:3,maxDepth:1,concurrency:2,maxModelCalls:14,maxCallsPerAgent:14,maxToolCalls:16,maxSearchAttempts:0,maxSandboxRuns:0,maxMinutes:5,maxInputTokens:250000,maxOutputTokens:30000,maxTokensPerCall:1536};
const objective=`Read both complete release logs. For each project select the latest APPROVED entry by sequence, ignoring proposed/rejected/withdrawn entries even when later. Produce result.json with exactly {"decisions":[{"project":string,"entry":string,"launch":string,"capacity":number,"source":string,"quote":string}]} and one decision per source. Quote the exact complete selected entry sentence through "seats.". Read real files; do not guess omitted text. You may write scratch notes and read them back. To avoid losing facts as context grows, checkpoint each source's selected entry into a small scratch file immediately after reading it before moving to another source. Only result.json is graded; scratch files are allowed. Final output must match original source facts.`;
const declaration={cases,model,limits,maximumCalls:126,objective,criterion:'Every selected entry, date, capacity, filename and exact quote matches separately derived source truth; both sources actually read; current-run output; complete run and required topology. All fields checked, no partial credit.',advantageRule:'For planned or autonomous separately: all three trials correct, and either (A) median latency at least 15% lower than single, with median calls and reported total tokens no greater, single also 3/3 correct; or (B) 3/3 correct against single at most 1/3, under identical root call/token/time caps. Otherwise advantage NOT_DEMONSTRATED. No post-hoc metric or threshold changes.',scope:'Synthetic context-pressure development comparison, three correlated template variants, fixed rotated arm order. Real local Qwen and workflow engine, read/write-only grants. Single baseline explicitly allowed scratch checkpoints. No universal swarm advantage or independent holdout claim. No semantic reviewer: exact source-grounded extraction is evaluated externally and identically for all modes, without exposing expected answers as contracts.'};
// Independent source-only extraction verifies corpus truth before any inference.
for(const c of cases){const derived=Object.entries(c.inputs).map(([source,text])=>{const matches=[...text.matchAll(/Entry ([^:]+): APPROVED\. Launch ([0-9-]+); capacity (\d+) seats\./g)];const last=matches.at(-1);if(!last)throw Error('No approval');return {project:source.startsWith('harbor')?'Harbor':'Summit',entry:last[1],launch:last[2],capacity:Number(last[3]),source,quote:last[0]};});if(JSON.stringify(derived)!==JSON.stringify(c.expected))throw Error('Source oracle mismatch');}
if(mode==='--prepare'){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify({createdAt:new Date().toISOString(),sourceHash:identity(),model:await modelIdentity(),declarationHash:sha(JSON.stringify(declaration)),declaration},null,2),{flag:'wx'});console.log('Frozen '+file);process.exit(0);}
const m=JSON.parse(fs.readFileSync(file,'utf8'));
async function frozen(){if(m.sourceHash!==identity()||m.declarationHash!==sha(JSON.stringify(declaration))||JSON.stringify(m.model)!==JSON.stringify(await modelIdentity()))throw Error('Frozen campaign drift');}
await frozen();const output=file.replace(/\.json$/,'-results.json');const report:any={status:'preflight',startedAt:new Date().toISOString(),manifestHash:sha(fs.readFileSync(file)),model:m.model,calls:0,trials:[]};fs.writeFileSync(output,JSON.stringify(report,null,2),{flag:'wx'});const save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));const budgets=new Store(path.resolve('data'));
const guarded:typeof infer=async(...args)=>{if(args[0].provider!=='ollama'||args[0].model!==model||args[0].endpoint!==endpoint||report.calls>=126)throw Error('Inference contract violated');report.calls++;save();return infer(args[0],args[1],AbortSignal.any([args[2],AbortSignal.timeout(90000)]),args[3]);};
try{
 report.admission=remainingRequestBudget(budgets,'inference');if(report.admission.remaining!==null&&report.admission.remaining<126)throw Error('Insufficient budget');report.status='running';save();
 for(const c of cases)for(const arm of c.order){
  await frozen();const directory=file.replace(/\.json$/,'')+'-'+c.id+'-'+arm;fs.mkdirSync(directory);const store=new Store(directory,budgets),engine=new SwarmEngine(store,()=>defaultSettings,guarded);const start=Date.now(),row:any={task:c.id,arm};report.trials.push(row);save();
  try{
   const agent={...structuredClone(INITIAL_AGENTS[0]),id:'manager',workspaceId:'ws-default',autonomyLevel:3,toolIds:['tool-files','tool-write-file'],llmConfig:{provider:'ollama',model,temperature:0,maxTokens:1536}};store.put('agents',agent.id,agent);store.put('projects','p',{id:'p',workspaceId:'ws-default',name:'Release decisions',members:[]});
   for(const [name,text]of Object.entries(c.inputs))engine.workspace.write('p',name,Buffer.from(text),0,'owner');
   const names=Object.keys(c.inputs);const worker=(name:string)=>`Read ${name} completely with tool-files. Select its latest APPROVED entry by sequence. Return a concise JSON object with project, entry, launch, capacity, source and exact quote of the selected entry sentence through seats. Do not write result.json; report the extracted object to the coordinator. Ignore later unapproved entries.`;
   const plan=names.map((name,i)=>({key:'reader'+i,name:'Reader '+i,role:'Source reader',instructions:worker(name),objective:worker(name),toolIds:['tool-files'],requiredToolIds:['tool-files'],toolSequence:['tool-files'],dependsOn:[],acceptanceCriteria:['Select latest approved entry and quote exact original text.']}));
   const instruction=arm==='single'?' Work alone. Checkpoint each source selection to a scratch file, then combine your notes.':arm==='planned'?' Wait for the two planned readers, then combine their extracted decisions.':' Delegate exactly two read-only source readers, one per log. Tell each to return project, entry, launch, capacity, source and exact approved-entry quote; wait for both, then combine their decisions yourself.';
   let run=engine.create({coordinatorId:'manager',projectId:'p',objective:objective+instruction,mode:'dynamic',allowedToolIds:['tool-files','tool-write-file'],requiredToolIds:['tool-write-file'],contracts:[{name:'result.json',kind:'exists'}],...(arm==='planned'?{plan}:{}),...(arm==='autonomous'?{requiredDepth:1}:{}),limits:{...limits,maxAgents:arm==='single'?1:3}},'logs-'+randomUUID());
   row.run=run;save();for(let tick=0;tick<90&&isSwarmLive(run.status);tick++){await engine.tick();run=engine.get(run.id);row.run=run;save();if(run.status==='waiting_approval')break;}
   if(isSwarmLive(run.status)){run=engine.cancel(run.id);row.error='Bounded tick limit';}row.run=run;
   let f:any,data:any;try{f=engine.workspace.file('p','result.json');data=JSON.parse(Buffer.from(f.base64,'base64').toString());row.artifact={sha256:f.sha256,version:f.version,runId:f.runId,content:data};}catch(e){row.artifactError=String(e);}
   const actual=Array.isArray(data?.decisions)?data.decisions:[];const correct=actual.length===2&&new Set(actual.map((x:any)=>x.source)).size===2&&c.expected.every(expected=>actual.some((a:any)=>Object.keys(expected).every(k=>a[k]===(expected as any)[k])));
   const reads=run.nodes.flatMap(n=>n.receipts.filter(r=>r.toolId==='tool-files'&&r.status==='succeeded').map((r:any)=>r.output?.name));
   row.checks={completed:run.status==='completed',currentArtifact:f?.runId===run.id,sourceTruth:correct,allSourceReads:names.every(n=>reads.includes(n)),topology:run.nodes.length===(arm==='single'?1:3)};row.passed=Object.values(row.checks).every(Boolean);
  }catch(e){row.error=e instanceof Error?e.message:String(e);row.passed=false;}finally{row.durationMs=Date.now()-start;engine.stop();store.close();save();console.log(JSON.stringify({task:c.id,arm,passed:row.passed,checks:row.checks,error:row.error,calls:row.run?.budget?.modelCalls,durationMs:row.durationMs}));}
 }
 await frozen();const median=(a:number[])=>a.sort((a,b)=>a-b)[1];const stats=['single','planned','autonomous'].map(arm=>{const rows=report.trials.filter((r:any)=>r.arm===arm);return {arm,passed:rows.filter((r:any)=>r.passed).length,total:rows.length,medianMs:median(rows.map((r:any)=>r.durationMs)),medianCalls:median(rows.map((r:any)=>r.run?.budget?.modelCalls??14)),medianTokens:median(rows.map((r:any)=>(r.run?.budget?.reportedInputTokens||0)+(r.run?.budget?.reportedOutputTokens||0)))}});
 const single=stats[0];report.summary=stats.map(s=>({...s,advantage:s.arm==='single'?'BASELINE':s.passed===3&&single.passed<=1?'BOUNDED_QUALITY_ADVANTAGE':s.passed===3&&single.passed===3&&s.medianMs<=single.medianMs*.85&&s.medianCalls<=single.medianCalls&&s.medianTokens<=single.medianTokens?'BOUNDED_LATENCY_ADVANTAGE':'NOT_DEMONSTRATED'}));report.status='finished';report.completedAt=new Date().toISOString();report.budgetAfter=remainingRequestBudget(budgets,'inference');save();console.log(JSON.stringify(report.summary));
}catch(e){report.status='blocked';report.error=String(e);save();throw e;}finally{budgets.close();}
