import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { Store } from '../src/server/store';import { SwarmEngine } from '../src/server/swarm';import { INITIAL_AGENTS } from '../src/data/initialData';import { defaultSettings } from '../src/server/providers';
const destination=process.argv[2];if(!destination)throw new Error('Pass an output JSON path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vac-extended-'));const store=new Store(dir);
const agent={...structuredClone(INITIAL_AGENTS[0]),id:'manager',workspaceId:'ws-default',displayName:'Coordinator',autonomyLevel:3 as const,toolIds:[],llmConfig:{provider:'ollama',model:'qwen3.5:9b',temperature:0,maxTokens:1024}};
store.put('agents',agent.id,agent);store.put('projects','project',{id:'project',workspaceId:'ws-default',name:'Extended acceptance',members:[]});
const engine=new SwarmEngine(store,()=>defaultSettings);const reports:any[]=[];const start=Date.now();
try{
 for(const kind of ['recursive','browser']){
  const r=engine.create({coordinatorId:agent.id,projectId:'project',mode:'dynamic',requiredDepth:kind==='recursive'?2:0,allowedToolIds:kind==='browser'?['tool-browser']:['tool-calculator'],requiredToolIds:kind==='browser'?['tool-browser']:[],browserPolicy:{allowedOrigins:kind==='browser'?['https://example.com']:[],allowActions:false},limits:{maxAgents:5,maxDepth:2,maxModelCalls:18,maxCallsPerAgent:6,maxMinutes:10},objective:kind==='recursive'?'Create ONE temporary specialist named TeamLead using tool-spawn-agent. TeamLead must itself create ONE temporary specialist named CalculatorLeaf, which must use tool-calculator to multiply 17 by 23 and return the verified answer. Give TeamLead only tool-calculator and explicit instructions to delegate the multiplication to CalculatorLeaf, then synthesize its receipt. You must not create CalculatorLeaf directly. Required topology is coordinator -> TeamLead -> CalculatorLeaf. Each child needs a distinct objective. After TeamLead returns, report the verified answer 391 and the nested delegation.':'Use tool-browser yourself with action navigate and url https://example.com. Then report the actual title and purpose stated on that page, with the URL. Do not spawn workers and do not guess from memory.'},'extended-'+kind+'-20260921');
  while(['queued','working','waiting_children'].includes(engine.get(r.id).status)){await engine.tick();const state=engine.get(r.id);console.log(kind,state.nodes.map(n=>`${n.name}:${n.status}:${n.calls}`).join(' | '));}
  const result=engine.get(r.id);const checks=kind==='recursive'?{completed:result.status==='completed',grandchild:result.nodes.some(n=>n.depth===2),calculator:result.nodes.some(n=>n.depth===2&&n.receipts.some(x=>x.toolId==='tool-calculator'&&x.output?.result===391)),final:result.result?.includes('391')===true}:{completed:result.status==='completed',browserReceipt:result.nodes[0].receipts.some(x=>x.toolId==='tool-browser'&&x.status==='succeeded'&&x.output?.title==='Example Domain'),network:(result.budget.browserRequests||0)>0};
  reports.push({kind,passed:Object.values(checks).every(Boolean),checks,result});fs.writeFileSync(destination,JSON.stringify({at:new Date().toISOString(),durationMs:Date.now()-start,passed:reports.every(r=>r.passed),reports},null,2));
 }
 if(reports.some(r=>!r.passed))process.exitCode=1;
}finally{engine.stop();store.close();fs.rmSync(dir,{recursive:true,force:true});}
